= Artifacts
:cljdoc-api-url: https://cljdoc.org/d/polylith/clj-poly/CURRENT/api

We assemble our `poly` bricks (xref:component.adoc[components] and xref:base.adoc[bases]) in xref:project.adoc[deployable projects] from which we build artifacts.

The base (a project typically has a single base) acts as the runtime entry point.

The `poly` tool has no say in what type of artifacts you build or how you xref:build.adoc[build] them.
Some artifact examples are:

* REST APIs
* Lambda functions
* Command line tools

[#libraries]
== Libraries

Polylith is not a perfect match for libraries if you plan to build more than one library from the same workspace.

The reason is that if the same component appears in multiple libraries with different versions in your classpath then there is a risk that you will end up with a mix of versions of those components, which may cause the code to not even compile, or maybe even worse, that you get unclear behavior.

But if you only have one library, like for example clj-poly, it will work fine. Then you can either choose to expose the library from an API component (see {cljdoc-api-url}/polylith.clj.core.api[clj-poly] as an example) or as an API base (both work equally well).

If you still choose to use Polylith, here is some advice.

Use the naming convention of `{libfamily}-{libname}-{version}.jar`.
For version `1.2.3` of libnames `foo` and  `bar` under libfamily `thingorama`, you'd build:

* `thingorama-bar-1.2.3.jar`
* `thingorama-foo-1.2.3.jar`

Including a lib family (e.g. the workspace name) makes it easier to find/sort libraries and makes it clear they belong to the same family of libraries.

The burden of ensuring no version mismatches occur when using multiple libraries from a family of libraries falls on the user of those libraries.
For example, a user may directly reference `thingorama-foo-1.2.3.jar`, but suppose some other library they depend on references `thingorama-bar-1.0.0.jar`.
It is up to the user to ensure they bring in the compatible `thingorama-bar-1.2.3.jar`.

Another possible approach is to build a single artifact for the lib family that includes all libraries:

* `thingorama-1.2.3.jar`

Issue https://github.com/polyfy/polylith/issues/212[212] explores the problems of isolating libraries that share components.
See Sean Corfield's comments for an excellent explanation of the issue.
