= Clojure CLI Tool

The `poly` tool's native argument syntax isn't compatible with Clojure CLI Tools argument syntax.
Using xref:install.adoc#install-as-clojure-cli-tool[poly as a Clojure CLI Tool] means using Clojure Tools key/value pair argument syntax.

NOTE: Our `poly` documentation only documents the `poly` native syntax.
This document acts as a small translation guide.

TIP: If using `poly` as a Clojure CLI Tool, consider using it only to launch a `poly` xref:shell.adoc[shell].
From there, you'll use the `poly` native argument syntax and avoid the mental tax of using a non-native argument syntax.

The `poly` tool native argument syntax has the following structure:

* the command, followed by
** zero or more entities (e.g., `create` can be followed by `component`), followed by:
*** named arguments (e.g., `project:example`)
*** flag arguments (e.g., `:loc`)
*** profiles (e.g., `+remote`)

Because Clojure Tools CLI exec args follows a key/value syntax, the argument structure for `-Tpoly` is:

* the command (which is the `:exec-fn`), followed by
** entity to name the first argument(s) to create or help,
** named arguments as key/value pairs (e.g., `project example`),
** flag arguments as keys with true or false values (e.g., `loc true`),
** profiles to list any profiles to enable, without the leading + (e.g., `profiles '[remote]'`).

For convenience, most arguments can be provided as symbols rather than requiring quoted strings:

[source,shell]
----
# strings have to be quoted for EDN and the shell:
clojure -Tpoly info project '"example"'
# the following shorthand is allowed:
clojure -Tpoly info project example
----

Both `project` and `profile` exist in singular form, taking a symbol or string, and in a plural form, taking a vector of symbols or strings:

[source,shell]
----
# select more than one project:
clojure -Tpoly info projects '[example cli]'
# select just one profile:
clojure -Tpoly info profile remote
----

Some poly commands treat `:brick` and `:project` as flag arguments and other expect `brick:name` or `project:name` as named arguments.
When using "exec args", the meaning is determined by whether the value is boolean or not:

[source,shell]
----
# select all projects:
clojure -Tpoly info project true # flag argument
# select a specific project:
clojure -Tpoly info project cli # named argument
----

Since the exec argument format for `create` is verbose, there are four shortcut arguments:

[source,shell]
----
# full create command syntax:
clojure -Tpoly create entity component name user
# shorthand:
clojure -Tpoly create c user
# similarly for b (base), p (project), and w (workspace)
clojure -Tpoly create w next-gen top-ns com.my-company
# is shorthand for:
clojure -Tpoly create entity workspace name next-gen top-ns com.my-company
----

Some commands allow you to specify multiple `entity` exec arguments.
Either use a single argument with `:` separators or use `entities` and a vector:

[source,shell]
----
clojure -Tpoly help entity create:component
# equivalent to:
clojure -Tpoly help entities '[create component]'
----
