= Configuration
:toc:

We have two categories of configuration:

1. Configuration used by the `poly` tool, stored in `workspace.edn` and `~/.config/polylith/config.edn`.
2. Configuration used by tools.deps, stored in `deps.edn` files in bricks and projects.

The content of all the configuration files also lives in the xref:workspace-structure.adoc[workspace structure],
under these top keys.

[source,shell]
----
poly ws get:configs:keys
----

[source,shell]
----
[:bases :components :projects :user :workspace]
----

== workspace

The workspace configuration file lives in `./workspace.edn`, and can be viewed with:

[source,shell]
----
poly ws get:configs:workspace
----

[source,clojure]
----
{:bricks {"user" {:ignore-files ["core.clj"]}}
 :compact-views #{}
 :default-profile-name "default"
 :interface-ns "interface"
 :projects {"command-line" {:alias "cl"}
            "development" {:alias "dev"}
            "user-service" {:alias "user-s"
                            :test {:create-test-runner my.test-runner/create}}}
 :tag-patterns {:release "v[0-9]*"
                :stable "stable-*"}
 :top-namespace "se.example",
 :vcs {:auto-add true
       :name "git"}}
----

A workspace contains these keys:

[%autowidth]
|===
| Key | Description

| `:bricks` | Allows us to turn off _Warning 206_ for one or more bricks, see xref:validations.adoc[validations].

| `:compact-view` | Controls the xref:dependencies.adoc#compact-view[output] from the xref:commands#info[deps]
and the xref:libraries.adoc#compact-view[output] from the xref:commands.adoc#libs[libs] command
so that they can be viewed in a more compact way, e.g.: `#{"deps" "libs"}`.

| `:default-profile-name` | The name of the profile that is automatically merged into the
xref:development.adoc[development] project if xref:profile.adoc[profiles] are used and no profile is given.
An example can be found
https://github.com/polyfy/polylith/blob/a4d9d2f3e50a2b76f36ed75c4a7ba7aa9a7b0db6/examples/doc-example/deps.edn#L14-L15[here].

| `:interface-ns` |
All namespaces within a component with this name, `interface`, or `ifc`, will be considered the component's interface.
The name set by this parameter is also used by the xref:commands.adoc#create-component[create component] command.

| `:projects` | A map that configures the projects in the workspace, see xref:ws-projects[projects] below.

| `:tag-patterns` | Holds the https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html[regex] patterns
that are used when searching for the most recent tag in git with a matching name,
explained xref:tagging.adoc[here], to calculate the latest committed sha,
that will be considered the _latest stable point in time_.

| `:top-namespace` | The top namespace used throughout the workspace in components and bases.

| `:vcs` | A map with two keys, where `:name` is set to "git" which is the only supported
https://en.wikipedia.org/wiki/Version_control[version control system] at the moment. +
The key `:auto-add` is a boolean flag that tells whether directories and files added by the
xref:commands#create[create] command should automatically be added to git or not.
|===

Only the `:top-namespace` attribute is mandatory, all other attributes will use their default values if missing.

[#ws-projects]
=== projects

The `:projects` key contains configuration for individual projects:

[source,shell]
----
poly ws get:configs:workspace:projects
----

[source,shell]
----
:projects {"command-line" {:alias "cl"
                           :test {:exclude ["mybrick"]}
                           :necessary ["helper"]}}
           "development" {:alias "dev"}
           "user-service" {:alias "user-s"
                           :test {:setup-fn project.command-line.test-setup/setup
                                  :teardown-fn project.command-line.test-setup/teardown}}
                        }}
----

Configuration for a specific project:

[%autowidth]
|===
| Key | Description

| `:alias` | This value is used in the output of the xref:commands.adoc#info[info] command
and various commands as an alternative value for the project name.
| `:necessary` | Allows us to turn off `Warning 206` for one or more bricks in the project, see xref:validations.adoc[Validations].
| `:test` | A map with test configuration for the project, see below.
|===

Test configuration under the `:test` key for a specific project:

[%autowidth]
|===
| Key | Description

| `:exclude` | Lists the bricks to be xref:testing.adoc#include-exclude[excluded] when running tests for the project.
| `:include` | Lists the bricks to be xref:testing#include-exclude[included] when running tests for the project.
| `:setup-fn` | The name of the function (namespace included) that will be executed before the tests are executed,
see xref:testing#setup-and-teardown[Test setup and teardown].
| `:teardown-fn` | The name of the function (namespace included) that will be executed after the tests have been executed,
see xref:testing#setup-and-teardown[Test setup and teardown].
|===

== projects

Each project has its own `deps.edn` configuration file.
The xref:development.adoc[development] config file lives in `./deps.edn`,
while other xref:project.adoc[projects] keep them in `projects/PROJECT/deps.edn`.

The content of a configuration file can be viewed with e.g.:

[source,shell]
----
poly ws get:configs:projects:command-line
----

[source,clojure]
----
{:config {:aliases {:test {:extra-deps {}
                           :extra-paths ["test"]}
                    :uberjar {:main se.example.cli.core}}
          :deps {org.apache.logging.log4j/log4j-core {:mvn/version "2.13.3"}
                 org.apache.logging.log4j/log4j-slf4j-impl {:mvn/version "2.13.3"}
                 org.clojure/clojure {:mvn/version "1.11.1"}
                 poly/cli {:local/root "../../bases/cli"}
                 poly/user-remote {:local/root "../../components/user-remote"}}}
 :name "command-line"
 :type :project}
----

[%autowidth]
|===
| Key | Description

| `:config` | The content of `deps.edn`.
| `:name` | The project name.
| `:type` | The type of configuration, set to `:project` for projects.
|===

== bases

Each xref:base.adoc[base] has its own `deps.edn` configuration file that lives in `bases/BASE/deps.edn`.

The content of a configuration file can be viewed with e.g.:

[source,shell]
----
poly ws get:configs:bases:cli
----

[source,clojure]
----
{:config {:aliases {:test {:extra-deps {}
                           :extra-paths ["test"]}}
          :deps {}
          :paths ["src" "resources"]}
 :name "cli"
 :type :base}
----

[%autowidth]
|===
| Key | Description

| `:config` | The content of `deps.edn`.
| `:name` | The base name.
| `:type` | The type of configuration, set to `:base` for bases.
|===

== components

Each xref:component.adoc[component] has its own `deps.edn` configuration file that lives in `components/COMPONENT/deps.edn`.

The content of a configuration file can be viewed with e.g.:

[source,shell]
----
poly ws get:configs:components:user
----

[source,clojure]
----
{:config {:aliases {:test {:extra-deps {}
                           :extra-paths ["test"]}}
          :deps {}
          :paths ["src" "resources"]}
 :name "user"
 :type :component}
----

[%autowidth]
|===
| Key | Description

| `:config` | The content of `deps.edn`.
| `:name` | The component name.
| `:type` | The type of configuration, set to `:component` for components.
|===

== user

Settings that are unique per developer/user are stored in `~/.config/polylith/config.edn`.
If you started using the `poly` tool from version `0.2.14-alpha` or earlier,
then the settings may be stored in `~/.polylith/config.edn`:

The content of the file can be viewed with:

[source,shell]
----
poly ws get:configs:user
----

[source,clojure]
----
{:color-mode "dark"
 :empty-character "."
 :thousand-separator ","}
----

[%autowidth]
|===
| Key | Description

| [[color-mode]] `:color-mode` | Defaults to "none" on Windows, and to "dark" on other operating systems.
Valid values are "none", "light" and "dark", see the xref:colors.adoc[Colors] section. Can be overridden with e.g.: `poly info color-mode:none`.
| `:empty-character` | Set to "." by default, and is used in the output from the xref:commands.adoc#deps[deps]
and xref:commands.adoc#libs[libs] commands.
| `:thousand-separator` | Set to "," by default. Use by the xref:commands.adoc#info[info] command for number >= 1000, when passing in `:loc`.
| `:m2-dir` | If omitted, the `.m2` directory will be set to `USER-HOME/.m2`.
Used by the xref:commands.adoc#libs[libs] command to calculate file sizes (KB).
|===

If `~/.config/polylith/config.edn` doesn't exist, it will be created the first time the xref:create-workspace[create workspace] command is executed.
