= Continuous Integration

In this document we will look at the general setup of CI.

When setting up continuous integration, we sometimes want to keep track of changes per project.
To support this we need to add tag patterns for the projects we want to build, e.g.:

[source,clojure]
----
 :tag-patterns {:stable "stable-*"
                :release "v[0-9]*"
                :myproject "myproject-*"}
----

When our build is triggered, e.g. via a webhook,
we can ask the _poly_ tool what projects have changed since the last successful build:

[source,clojure]
----
poly ws get:changes:changed-or-affected-projects since:myproject
----

Output, e.g.:

[source,clojure]
----
["invoicer" "myproject"]
----

If _myproject_ is returned, which is the case here, then we know that this project needs to be built and deployed,
as long as all tests also pass. After a successful build, we tag the repository, e.g.:

[source,shell]
----
git tag myproject-1
----

We want to keep the release tags, which is the reason each tag gets its own unique tag name,
e.g. _myproject-1_, _myproject-2_, and so on. It's not important that the IDs are sequential.
The tool will always sort them by the order they exist in git anyway.

If the CI build is set up so that it builds all projects in one go,
then we could first start by asking what projects we have:

[source,shell]
----
poly ws get:projects:keys skip:dev
----

The _skip:dev_ parameter tells the tool to ignore the development environment
(we are not interested in deploying dev).
More than one project can be ignored, e.g. _skip:dev:invoicer_,
where both project names and aliases can be used.

Then we can ask for changed or affected projects:

[source,shell]
----
poly ws get:changes:changed-or-affected-projects since:release skip:dev
----

Here we rely on release-* tags that mark the whole repo as released.

== How this repo sets up CI and deployment
:toc:
:toclevels: 4

The polylith repository has a continuous integration and deployment setup via https://circleci.com[CircleCI].
The setup has two workflows, one for regular validation and testing, and another one for deployments.
Both workflows have several jobs that validate, test, and deploy the artifacts to
https://clojars.org/search?q=polylith[Clojars] and GitHub as https://github.com/polyfy/polylith/releases[releases].

You can find the CircleCI configuration file link:../.circleci/config.yml[here].

=== Validate Workflow

The main responsibility of this workflow is to validate the workspace and run the tests incrementally for all commits to all branches.
Specifically for the _master_ branch, it also marks the commit as stable via a git tag.

==== Jobs

===== Check

This job runs the check command from the _poly_ tool as follows: `clojure -M:poly check`.
If there are any errors in the xref:workspace.adoc[workspace], it returns with a non-zero exit code and the CircleCI workflow stops at this stage.
If there are any warnings printed by the tool, it will be visible in the job's output.

===== Info

This job runs the following commands, one after another:

* `clojure -M:poly ws`
** Prints the current workspace as data in https://github.com/edn-format/edn[edn] format.
* `clojure -M:poly info`
** Prints workspace information.
* `clojure -M:poly deps`
** Prints the dependency information
* `clojure -M:poly libs`
** Prints all libraries that are used in the workspace.

After this job is done, all this information will be available in the jobs output for debugging purposes, if needed.
You can read more about available commands xref:commands.adoc[here].

===== Test

This job runs all the tests for all the bricks and projects that are directly or indirectly changed since the last stable point in time.
The _poly_ tool supports incremental testing out-of-the-box by using stable point marks in the git repository.
It runs the following command: `clojure -M:poly test :project`.
If any of the tests fail, it will exit with a non-zero exit code and the CircleCI workflow stops at this stage.
Information about the passed/failed tests will be printed in the job's output.

===== Mark as stable

This job only runs for the commits made to the _master_ branch.
It adds (or replaces if already exists) the `stable-master` tag to the repository.
At this point in the workflow, it is "proven" that the Polylith workspace is valid and all of the tests are passed,
and it's safe to mark this commit as stable.

It does that by running the following commands, one after another:

* `git tag -f -a &quot;stable-$CIRCLE_BRANCH&quot; -m &quot;[skip ci] Added Stable Polylith tag&quot;`
** Creates or moves the tag.
* `git push origin $CIRCLE_BRANCH --tags --force`
** Pushes the tag back to the git repository.

=== Deploy Workflow

The main responsibility of this workflow is to validate the workspace,
run the tests incrementally and deploy artifacts to Clojars and GitHub releases.
It only runs when a new tag is pushed to the git repository with the following regex pattern: `/^v.*/`.

==== Jobs

===== Check Build

This job runs the xref:commands.adoc#check[check] command as follows: `clojure -M:poly check since:previous-release`.
Please note the last part of the command where we specifically tell the _poly_ tool to check the workspace
since the last release, instead of the last stable point in time. If there are any errors in the Polylith workspace,
it returns with a non-zero exit code and the CircleCI workflow stops at this stage.
If there are any warnings printed by the tool, it will be visible in the job's output.

===== Info

This job runs the following commands, one after another.
Please note the last part of the command, where we specifically tell the tool to check the workspace
since the last release, instead of the last stable point in time:

* `clojure -M:poly ws since:previous-release`
** Prints the current workspace as data in https://github.com/edn-format/edn[edn format].
* `clojure -M:poly info since:previous-release`
** Prints workspace information.
* `clojure -M:poly deps since:previous-release`
** Prints the dependency information
* `clojure -M:poly libs since:previous-release`
** Prints all libraries that are used in the workspace.

After this job is done, all this information will be available in the jobs output for debugging purposes, if needed.
You can read more about available commands xref:commands.adoc[here].

===== Test

This job runs all the tests for all the bricks that are directly or indirectly changed since the last release.
It runs the following command: `clojure -M:poly test :project since:previous-release`.
If any of the tests fail, it will exit with a non-zero exit code, and the CircleCI workflow stops at this stage.
Information about the passed/failed tests will be printed in the job's output.

===== Deploy

This job deploys the changed projects to Clojars. It's easy to deploy incrementally with the _poly_ tool.
Changed projects are calculated since the latest release.
You can see how it's done https://github.com/polyfy/polylith/blob/master/build.clj[here].
In a nutshell, it executes `poly ws get:changes:changed-or-affected-projects skip:dev since:previous-release`
and only deploys the returned projects.

===== Create Artifacts

This job creates two types of artifacts per changed project, an AOT compiled uberjar and a package that can be used to deploy https://brew.sh[Homebrew].
Created artifacts can be found in the artifacts section of this job's output.

===== Publish GitHub Release

This job uploads the artifacts created after the previous job and uploads them to a new release in GitHub.
It makes use of the https://github.com/tcnksm/ghr[GHR] tool in order to create a new release on GitHub and upload the artifacts.
