= Continuous Integration
:toc:

The `poly` tool stays out of your way on how you xref:build.adoc[build] your xref:project.adoc[deployable project] xref:artifacts.adoc[artifacts] on your continuous integration server.

Here, we go over a couple of xref:tagging.adoc#release[tagging and release] strategies for you to consider.

== Build and Release All

If you don't have many projects, you might want to build and deploy for all deployable projects:

. Run tests.
. Git tag the release.
. Build artifacts for all deployable projects.
. Deploy all built artifacts.

== Build and Release for Changed Projects Only

Perhaps you want to optimize your flow to only build and deploy what has changed:

. Run tests.
. Ask `poly` what deployable projects have changed since the last release:
+
[source,shell]
----
poly ws get:changes:changed-or-affected-projects since:release skip:dev # <1>
----
<1> We `skip:dev` because it is not a deployable project
. Git tag the release.
. Build artifacts for all _changed_ deployable projects.
. Deploy all built artifacts.

If you were to swap steps 2 and 3, you would use `since:previous-release` instead of `since:release`