= Developing poly

Here we will go through things that primarily have value if you are a developer of the `poly` tool itself.
Feel free to read what's in here, and hopefully you will pick up something of value.

== Parameters

There are a few parameters that are either rarely used, added to simplify maintenance work with the https://github.com/polyfy/polylith[polylith] codebase, or used in special circumstances.
For these reasons, they are not suggested by the autocomplete when in a xref:commands.adoc#shell[shell].
What most of them have in common is that they are used to control the output of the different `poly` commands.

[[all]]
=== all

If passing in `:all` to the xref:commands.adoc[help] command, the help for the  xref:commands.adoc#migrate[migrate] command will also be included (it will also be included if the workspace needs to be migrated):

[source,shell]
----
poly help :all
----

If `:all` is passed in when starting a shell:

[source,shell]
----
poly :all
----

...the autocomplete for all available parameters will be activated, including those that are rarely used (and are mostly in the way) and parameters that only make sense when developing the `poly` tool itself.
For example, `:fake-poly` is only used to fake that we use a released version of the `poly` tool.

=== changed-files

This parameter is used to fake changes of files, and is used for testing purposes when developing the `poly` tool itself, e.g:

[source,shell]
----
poly info changed-files:components/file/polylith/clj/core/user_input/core.clj
----

More than one file can be marked as changed by separating them with colons (the autocomplete only works for the first file at the moment).

It's enough to include the brick or project name plus a slash, and the tool will treat the brick/project as changed, e.g.:

[source,shell]
----
poly info changed-files:bases/mybase/:components/mycomponent/:projects/myproject/
----

=== fake-sha

This parameter can be passed in to fake a `sha` when executing the xref:commands.adoc#info[info] command, which is used when taking screenshots for this documentation.

[source,shell]
----
poly info fake-sha:c91fdad
----

=== fake-tag

This parameter can be passed in to fake a `tag` when executing the xref:commands.adoc#info[info] command, which sometimes is used when taking screenshots for this documentation, e.g.:

[source,shell]
----
poly info fake-tag:stable-lisa
----

The tag can be removed with:

[source,shell]
----
poly info fake-tag:
----

=== fake-poly

This parameter is used to fake that we are using a non-snapshot version of the `poly` tool, and not the `polyx` tool.

[source,shell]
----
# Excludes "-SNAPSHOT" from the version at the top of the help output:
poly help :fake-poly
# Excludes "-SNAPSHOT" from the Polylith ascii art logo:
poly :fake-poly
----

=== latest-sha

This parameter is used to tell the tool to fetch the latest sha from the git repo (otherwise it's not populated), e.g.:

[source,shell]
----
poly ws get:settings:vcs:polylith:latest-sha :latest-sha
----

=== no-changes

This parameter can be used to fake that no changes have been made since the last stable point in time, and can be used when taking a screenshot of the xref:commands.adoc#info[info] command without getting the `*` characters.

[source,shell]
----
# Returns no rows:
poly diff :no-changes
# Gets rid of the * characters:
poly info :no-changes
# ...has the same effect as:
poly info changed-files:
----

=== no-exit

When the `poly` tool is executed, it exits with `System/exit` internally, see https://github.com/polyfy/polylith/blob/edaef89207c2852010132e863ae87ebba5bedc5b/bases/poly-cli/src/polylith/clj/core/poly_cli/core.clj#L33[poly-cli].
If executing the `poly` tool from a REPL, this will also exit the REPL.
To avoid that, we can pass in https://github.com/polyfy/polylith/blob/9053b190d5f3b0680ac4fe5c5f1851f7c0d40830/bases/poly-cli/src/polylith/clj/core/poly_cli/core.clj#L31-L32[:no-exit].

If we execute e.g. `poly info :no-exit` we have to press `<ctrl>+C` to exit, which is not so useful!

=== replace

This parameter is used to manipulate the output from the xref:commands.adoc#ws[ws] command.
When we execute `poly ws get:settings:user-home` it will return something like "/Users/joakimtengstrand".
We can tell the xref:commands.adoc#ws[ws] command to search for strings (using regular expressions) and replace the occurrences with another string, e.g. (assumes that $HOME is set):

* `poly ws get:settings:user-home replace:$HOME:MY-HOME` Outputs: "MY-HOME".

* `poly ws get:settings:user-config-filename replace:$HOME:MY-HOME` Outputs: "MY-HOME/.polylith/config.edn".

* `poly ws get:settings:user-config-filename replace:$HOME:MY-HOME:config.edn:USER-CONFIG` Outputs: "MY-HOME/.polylith/USER-CONFIG".

* `poly ws get:settings:vcs:stable-since:sha replace:"[0-9]+":"*"` Outputs "*e*d*b*cee*fb*e*ff*fafcf".
Here we need to surround the regular expressions with "" for the terminal to ignore the special characters.

== Documentation

We strive to write great documentation for our Polylith users.

https://asciidoctor.org/docs/what-is-asciidoc/#what-is-asciidoc[AsciiDoc] is thoughtfully designed for writing articles; we like that, so all of our articles are written in AsciiDoc.

Some conventions we have found helpful are:

* Write one sentence per line.
Among other https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line[things], this helps us to avoid run-on sentences.
* These particular docs cover an implementation of a Polylith tool, so use the concrete `poly` instead of the abstract "Polylith tool".
* For command-line `poly create workspace top-ns:my-ns branch:my-branch :commit` refer to:
** `create workspace` as a command
** `top-ns:my-ns`, `branch:my-branch` and `:commit` as arguments
* Always link to referenced commands and concepts to make it easier for readers to explore and dig into details.
* Use "we" when talking from the Polylith core team and "you" when directing the reader through some steps or a tutorial.

We host our docs on https://cljdoc.org/d/polylith/clj-poly[cljdoc].

=== Run cljdoc locally

If we are maintainers of the documentation, we may want to see how it looks in https://cljdoc.org[cljdoc].
To do that we can start by cloning the https://github.com/polyfy/polylith[polylith] repository:

[source,shell]
----
git clone git@github.com:polyfy/polylith.git
----

This is how the help for the https://github.com/polyfy/polylith/blob/dae4bfb16e1e478ce815d1f223b57c269128d324/bb.edn#L20[doc-preview]
command looks like:

[source,shell]
----
cd polylith
bb doc-preview help

Commands:
 start   Start docker containers supporting cljdoc preview
 ingest  Locally publishes poly for cljdoc preview
 view    Opens cljdoc preview in your default browser
 stop    Stops docker containers supporting cljdoc preview
 status  Status of docker containers supporting cljdoc preview
 help    Show this help
----

We can now start the server and publish the documentation locally (which takes a few minutes):

[source,shell]
----
bb doc-preview start
bb doc-preview ingest
----

Now we can start a shell from the `polylith` directory:

[source,clojure]
----
poly :local
----

Now we can start a xref:commands.adoc#shell[shell] from our workspace:

[source,shell]
----
cd myws
clojure -M:poly :local
----

The `:local` flag will tell the xref:doc.adoc[doc] command to open pages on `http://localhost:8000` instead of `https://cljdoc.org`.

=== Open pages in GitHub

If we are in the `polylith` workspace root directory, we can start a shell with `:local` and then open the corresponding file in GitHub, e.g.:

[source,shell]
----
cd polylith
clojure -M:poly :local
polylith$ doc page:component :github
----

If we have checked out another branch than `master`, the page will be opened in that branch.

But if we start a xref:commands.adoc#shell[shell] from another workspace than `polylith`,
we will need to tell on which branch the GitHub file should be opened up in, otherwise it will use `master` as default:

[source,shell]
----
cd myws
clojure -M:poly :local
polylith$ doc page:component branch:issue-318 :github
----

If we don't run a local server, we may want to always open pages on GitHub instead of cljdoc, which can be achieved by passing in `:github` when starting a shell:

[source,shell]
----
cd myws
clojure -M:poly :github
polylith$ doc page:component
----

If the shell is started from the `polylith` repository as in this example, then pages will automatically be opened in the current branch, and we don't have to pass in `branch:BRANCH`, otherwise the `master` branch will be used as fallback.

====
NOTE: The documentation lives under the https://github.com/polyfy/polylith/tree/master/doc[doc] directory in the `polylith` repository from which the https://cljdoc.org/[cljdoc] based documentation is generated.
The documentation is triggered when we release the `poly` tool and when we push commits to the `master` branch, which is described xref:polylith-ci-setup.adoc#releases[here].
====

If we want to open the pages in another branch, we have to give the branch, e.g.:

[source,shell]
----
cd myws
clojure -M:poly :github branch:issue-318
polylith$ doc page:component
----

=== Reloading changes

Sometimes the cljdoc platform that builds the documentation has been updated, and in that case we need to restart the Docker container to get the latest version:

[source,shell]
----
bb doc-preview stop
bb doc-preview start
----

If the polylith codebase has changed, we need to run `ingest` again (the server does not need to be restarted):

[source,shell]
----
bb doc-preview ingest
----

Examples of when we might want to do this

* When we have switched branch with `git checkout`
* When we have received more commits with `git pull`
* When we have pushed commits with `git push` (commits have to be pushed for the `ingest` to work)

== Use the local version of polylith

Now when the `polylith` workspace is cloned locally, it can be accessed directly from other workspaces if we want.
This can be achieved by replacing the `:poly` alias, in e.g. `myws/deps.edn`:

[source,clojure]
----
    ...
    :poly {:main-opts ["-m" "polylith.clj.core.poly-cli.core"]
           :extra-deps {polylith/clj-poly {:local/root "../polylith/projects/poly"}}}

----

Make sure the "../polylith/projects/poly" path points to the `poly` project in the cloned `polylith` workspace directory.
