= Developing poly
:toc:

The curious are most welcome, but we wrote this document for folks who are (or want to) contribute to the development `poly` itself.

== Contributing

We very much appreciate contributions from the community.

=== Issues First Please

If you have an idea or a fix, please do raise a GitHub issue before investing in any coding effort.
That way, we can discuss first.
Writing code is the easy part; maintaining it forever is the hard part!

That said, if you notice a simple typo, a PR without an issue is fine.

TIP: We are also happy to chat about your idea or fix on the Clojurians https://clojurians.slack.com/messages/C013B7MQHJQ[polylith] channel.

=== Include Tests and Docs

We expect you to include/update tests for your change.

You've probably gotten the sense that providing good docs for our users is important to us.
When your change affects our docs or needs to be described for our users, we expect you to do so.

Add a brief line summarizing your change to link:/next-release.md[next-release.md].
The `poly` core team moves the content in this file to the changelog for each stable https://github.com/polyfy/polylith/releases[release].

=== Submitting a Pull Request

Please never force push on your PR, as this makes reviewing incremental changes impossible for us.
When we merge your PR, we'll usually squash it, so that will clean up any rambling work-in-progress.

== Special `poly` Arguments

Some `poly` arguments are special-case or `poly` developer-focused.
For this reason, the xref:commands.adoc#shell[shell] will not include these arguments in its autocomplete suggestions xref:#all-shell[by default].

Most special arguments tweak the output of the various `poly` commands.

[[all-shell]]
=== `all` - `shell`
By default, the xref:commands.adoc#shell[shell] does not suggest special `poly` arguments because they are irrelevant and inappropriate for typical users of `poly`.
If you are developing `poly` itself, suggesting special `poly` arguments can be appropriate and meaningful.
To start a shell with autocomplete suggestions enabled for all `poly` arguments:

[source,shell]
----
poly :all
----

=== `changed-files`

Have `poly` react as if specified files have changed.
We use this to support testing `poly` itself.

[source,shell]
----
poly info changed-files:components/file/src/polylith/clj/core/file/core.clj
----

More than one file can be faked as changed by separating them with colons.

****
Although multiple files are supported, the `shell` autocomplete support works only for the first file.
****

Specify a brick or project path with a trailing forward slash, and `poly` will treat the brick or project as changed:

[source,shell]
----
poly info changed-files:bases/mybase/:components/mycomponent/:projects/myproject/
----

=== `fail-if-nothing-to-test`

Forces the xref:commands.adoc#test[test] command to return a non-zero code (1) if there are no tests to run.

[source,shell]
----
poly test :fail-if-nothing-to-test
----

=== `fake-sha`

Fake the Git `sha` output by the xref:commands.adoc#info[info] command.
We use this to generate consistent `info` output and screenshots for our documentation.

[source,shell]
----
poly info fake-sha:c91fdad
----

=== `fake-tag`

Fake the Git `tag` for output by the xref:commands.adoc#info[info] command.
We sometimes use this to generate consistent `info` output and screenshots for our documentation.

[source,shell]
----
poly info fake-tag:stable-lisa
----

If you want no Git `tag` to be shown in `info` output:

[source,shell]
----
poly info fake-tag:
----

=== `fake-poly`

Fake that you are using a stable production release of `poly` when you might actually be using a `SNAPSHOT` release, `polyx`, or both.

[source,shell]
----
poly help :fake-poly # <1>
polyx :fake-poly # <2>
----
<1> Excludes `-SNAPSHOT` from the version at the top of the help output
<2> Shows `poly` instead of `polyx` and excludes `-SNAPSHOT` from the Polylith ASCII art logo

This can be handy when capturing output for docs.

=== `hide-lib-size`

If `:hide-lib-size` is given to the xref:commands.adoc#libs[libs] command, values in the `KB` column appear as `-`:

[source,shell]
----
poly libs :hide-lib-size # <1>
----

This is used in tests to guarantee that the output will look the same, regardless if a library has been downloaded or not.

=== `latest-sha`

Populate the `latest-sha` from your Git repository in your workspace structure (by default, `poly` does not populate this value).

[source,shell]
----
poly ws get:settings:vcs:polylith:latest-sha :latest-sha
----

=== `no-changes`

Fake that there are no changes to your workspace since the last xref:tagging.adoc[stable point in time]; can be useful when generating output for docs.

[source,shell]
----
# Returns no rows:
poly diff :no-changes
# Gets rid of the * characters:
poly info :no-changes
# ...has the same effect as:
poly info changed-files:
----

=== `no-exit`

By default, `poly` explicitly exits via `System/exit` .
If executing `poly` from a REPL, this will also exit the REPL, which probably isn't what you want.
To avoid that, specify `:no-exit`.

See link:/bases/poly-cli/src/polylith/clj/core/poly_cli/core.clj[poly-cli source] `comment` block for plenty of examples.

****
Outside of REPL support, `:no-exit` has little use.
If you run, e.g.:
[source,shell]
----
poly info :no-exit
----
You'll have to press kbd:[Ctrl+C] to exit!
****

=== `replace`

Manipulate output from the xref:commands.adoc#ws[ws] command.

You can tell the `ws` command to search for strings (using regular expressions) and replace the occurrences with another string.

[source,shell]
----
poly ws get:settings:user-home
----
On Joakim's system, output is:
[source,text]
----
"/Users/joakimtengstrand"
----

But maybe we want some repeatable output for test or documentation purposes, regardless of which user is running the `ws`.
Assuming that your `HOME` environment variable is set appropriately and that you are running from your OS shell (not poly's `shell`):

**An example:**
[source,shell]
----
poly ws get:settings:user-home replace:$HOME:MY-HOME
----
Outputs a user-generic:
[source,text]
----
"MY-HOME"
----

**Another example:**
[source,shell]
----
poly ws get:settings:user-config-filename replace:$HOME:MY-HOME
----
Outputs a user-generic:
[source,text]
----
"MY-HOME/.polylith/config.edn"
----

**An example with multiple replacements:**
[source,shell]
----
poly ws get:settings:user-config-filename replace:$HOME:MY-HOME:config.edn:USER-CONFIG
----
Outputs:
[source,text]
----
"MY-HOME/.polylith/USER-CONFIG"
----

**Sometimes you need to deal with your OS shell escaping rules and add, for example, `""`.**
[source,shell]
----
poly ws get:settings:vcs:stable-since:sha replace:"[0-9]+":"*"
----
The output will vary because git shas are unique, but on Joakim's system once:
[source,text]
----
"*e*d*b*cee*fb*e*ff*fafcf"
----

[[set]]
=== `set`

The poly tool starts by reading the workspace into a representation in memory.
Before it continues with the next step, to provide that data structure to a command, we get the chance to set a value.

If we want to change the behaviour of the `libs` command, we can update configuration read from _workspace.edn_:

[source,clojure]
----
 ...
 :validations {:inconsistent-lib-versions {:type :warning
                                           :exclude []}}
----

Like this:

[source,shell]
----
// Set :type to :error
poly libs set:configs:workspace:validations:inconsistent-lib-versions:type value:error type:keyword

// Set :exclude to ["clj-time/clj-time"]
poly libs set:configs:workspace:validations:inconsistent-lib-versions:exclude value:clj-time/clj-time type:strings
----

If a value already exists in the workspace structure, it will be converted to the type of that value.
If it's a non-existing value, the type will be a `string` if not explicitly set.
Use `type` to explicitly give a type.

[cols="4,5,8"]
|===
| type | string value | converted to

| `boolean`
| `true`
| the boolean value `true`

| `long`
| `123`
| the long value `123`

| `keyword`
| `warning`
| the keyword `:warning`

| symbol
| `hi`
| the symbol `hi`

| `booleans`
| `true:false`
| A vector `[true false]`

| `longs`
| `123`
| A vector `[123]`

| `strings`
| `hi:again`
| A vector `["hi" "again"]`

| `keywords`
| `hi:again`
| A vector `[:hi :again]`

| `symbols`
| `hi:again`
| A vector `[hi again]`

|===




== Documentation

We strive to write great documentation for our Polylith users.

https://asciidoctor.org/docs/what-is-asciidoc/#what-is-asciidoc[AsciiDoc] is thoughtfully designed for writing articles; we like that, so all of our articles are written in AsciiDoc.

Some conventions we have found helpful are:

* Write one sentence per line.
Among other https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line[things], this helps us to avoid run-on sentences.
* These particular docs cover an implementation of a Polylith tool, so use the concrete `poly` instead of the abstract "Polylith tool".
* For command-line `poly create workspace top-ns:my-ns branch:my-branch :commit` refer to:
** `create workspace` as a command
** `top-ns:my-ns`, `branch:my-branch` and `:commit` as arguments
* Link to referenced commands and concepts to make it easier for readers to explore and dig into details.
* Use the https://docs.asciidoctor.org/asciidoc/latest/macros/keyboard-macro/[AsciiDoc keyboard macro] for keyboard shortcuts.
For an example usage, see xref:shell.adoc#quit[Shell page].
* Use "we" when talking from the Polylith core team and "you" when directing the reader through some steps or a tutorial.
* Try to maintain a casual and friendly tone.

=== Diagrams

We create our diagrams with the ever-so-awesome https://inkscape.org/[Inkscape].
Inkscape's native format is `.svg`.
We export to `.png` for use in our documentation.
We keep the source `.svg` beside the exported `.png` in our GitHub repo.

We store doc images under `./doc/images/`, for example for the overview diagram in xref:/doc/doc.adoc[./doc/doc.adoc] doc:

* Inkscape source: link:/doc/images/doc/doc-overview.svg[./doc/images/doc/doc-overview.svg]
* Exported png: link:/doc/images/doc/doc-overview.png[./doc/images/doc/doc-overview.png]

Generated images (currently from `bb create-example` via `polyx`) are grouped with their related images but are prefixed with an `output` dir.
This strategy helps us distinguish hand-crafted images from generated ones and reminds us not to edit images in the `output` dirs.

Sometimes, we'll annotate a generated image.
We do so via an Inkscape SVG file and link (rather than embed) the generated image.
As of this writing, if any of these images change, the `.svg` will have to be manually re-exported to its `.png`.

Tips:

* Use a transparent background.
* We host our docs on https://cljdoc.org[cljdoc], which uses a light theme.
Folks viewing our docs on GitHub might have opted for a dark theme, so choose colors that will also be dark-theme friendly.
* Choose cross-platform-friendly fonts.
`Courier New` and `Arial` seem to be what existing diagrams use.
If you are a Linux user, you can install these as part of Microsoft's fonts.

=== Cljdoc

We host our docs on https://cljdoc.org/d/polylith/clj-poly[cljdoc], which generates docs for our:

* API by analyzing our source code from our release jar
* pages (which cljdoc calls "articles") which cljdoc finds under link:/doc[doc], and whose layout is defined by link:/doc/cljdoc.edn[doc/cljdoc.edn].

We have cljdoc build our docs each time we release to clojars.
This includes `SNAPSHOT` releases, which we create for every successful push to `master`.
See xref:polylith-ci-setup.adoc#releases[Polylith CI Setup] for more details.

[[local-cljdoc]]
=== Previewing Cljdoc Locally

When making changes to docs, you can preview what they will look like on https://cljdoc.org[cljdoc].
If you have not already done so, clone the https://github.com/polyfy/polylith[polylith] repository:

[source,shell]
----
git clone git@github.com:polyfy/polylith.git
----

Take a look at the help for our babashka `doc-preview` task:

[source,shell]
----
$ cd polylith
$ bb doc-preview help

Commands:
 start   Start docker containers supporting cljdoc preview
 ingest  Locally publishes poly for cljdoc preview
 view    Opens cljdoc preview in your default browser
 stop    Stops docker containers supporting cljdoc preview
 status  Status of docker containers supporting cljdoc preview
 help    Show this help
----

Start the server and publish the documentation locally (the first `start` will take some time to download the cljdoc docker image, and `ingest` is on the slow side):

[source,shell]
----
$ bb doc-preview start
$ bb doc-preview ingest
----

TIP: Commit and push all your changes before you `ingest`.

Bring the docs up in your web browser with:
----
bb doc-preview view
----

[[local]]
=== Poly Shell and Local Cljdoc

If you are in the `polylith` workspace root directory (which is also the git repo root dir), you can start a xref:commands.adoc#shell[shell] specifying the `:local` argument to tell the xref:commands.adoc#doc[doc] command to open pages on `\https://localhost:8000` instead of `\https://cljdoc.org`.

[source,shell]
----
clojure -M:poly :local
----

Now docs open in your browser against the xref:#local-cljdoc[locally running cljdoc]:
[source,shell]
----
polylith$ doc page:component
----

=== Refreshing Local Cljdoc Preview

From time to time, there is a new release of cljdoc.
To pick it up:

[source,shell]
----
bb doc-preview stop
bb doc-preview start
----

When you've changed the polylith codebase, you need to run `ingest` again (no need to `stop` and `start`):

[source,shell]
----
bb doc-preview ingest
----

Examples of when you might want to `ingest` are when you have:

* Switched to a different git branch.
* Pulled changes down with `git pull`.
* Pushed commits with `git push`.
You must commit and push your changes for `ingest` to function; doing so from a branch is fine.

=== Open Page Source in GitHub

Fire up a xref:commands.adoc#shell[shell]:
[source,shell]
----
clojure -M:poly :local
----

****
In addition to xref:#local[opening pages locally instead of on cljdoc.org], the `:local` argument also enables, for convenience, `shell` autocompletion for the `:github` argument.
Feel free to also specify xref:#all-shell[:all].
****

Specify the `:github` argument to bring up the page in your web browser on GitHub:
[source,shell]
----
polylith$ doc page:component :github
----

If you started your shell from the `polylith` repository (not a fork), then pages will automatically be opened in your current working branch; otherwise, pages will open on the `master` branch.

To choose a specific `branch`:
[source,shell]
----
polylith$ doc page:component branch:issue-318 :github
----

If you aren't running cljdoc locally, you may want to always open pages on GitHub instead of cljdoc; specify the `:github` argument when starting a shell:

[source,shell]
----
clojure -M:poly :github
polylith$ doc page:component
----

== Referencing a Local `poly`

So long as you've cloned the `polylith` workspace locally, you can access it from other workspaces.
This can be convenient when testing another workspace but wanting to use a local `polylith` that has some work in progress.

Let's say you have cloned the https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app[Realworld example app] as a sibling to the `polylith` repo in your directory tree.

You could then replace the `:poly` alias in `clojure-polylith-realworld-example-app/deps.edn`:

[source,clojure]
----
    ...
    :poly {:main-opts ["-m" "polylith.clj.core.poly-cli.core"]
           :extra-deps {polylith/clj-poly {:local/root "../polylith/projects/poly"}}} ;; <1>

----
<1> Notice the `..` relative path to `poly`

And now, from the `clojure-polylith-realworld-example-app` dir, you can launch local `poly` via, e.g.:

[source,shell]
----
clojure -M:poly
----

[#clojars-downloads]
== Number of downloads on Clojars

The number of downloads per version can be checked by executing:

[source,shell]
----
bb scripts/clojars-stats.bb
----

[source,shell]
----
Version       | Downloads
-------------------------
0.3.31        |       220
0.3.30        |     1,165
0.3.0         |       618
0.2.22        |     4,655
0.2.21        |    14,786
0.2.20        |     3,633
0.2.19        |    14,532
0.2.18        |    24,758
0.2.17-alpha  |   111,424
0.2.16-alpha  |        62
0.2.15-alpha  |       679
0.2.14-alpha  |     2,166
0.2.13-alpha  |     2,070
0.2.12-alpha  |       426
0.2.0-alpha11 |       100
0.2.0-alpha10 |        82
0.1.0-alpha9  |       112
0.1.0-alpha8  |        75
0.1.0-alpha7  |        81
0.1.0-alpha6  |        76
0.1.0-alpha5  |        77
0.1.0-alpha4  |        77
0.1.0-alpha3  |        78
0.1.0-alpha2  |        82
0.1.0-alpha1  |        76
----

== SNAPSHOT Releases & Caching

https://github.com/clojure/tools.deps[Clojure tools.deps] only checks for updates once per day by default.

This caching behavior means users referencing a specific `SNAPSHOT` will be more likely to temporarily be on an older release if you frequently release under the same `SNAPSHOT` version.

Users can https://clojure.org/reference/deps_and_cli#_classpath_caching[-Sforce] a check for an update, but most probably won't think to do that.


[#create-a-snapshot-release]
== Create a SNAPSHOT release

Make a `0.2.20-SNAPSHOT 34` release:

. Run all tests: `poly test :all`
. Update the `version` component and ensure that:
  - https://github.com/polyfy/polylith/blob/87aeb2ce093f31449827fb19d189e4ad0f80859d/components/version/src/polylith/clj/core/version/interface.clj#L24-L26[version] is set to `0.2.20`.
  - https://github.com/polyfy/polylith/blob/87aeb2ce093f31449827fb19d189e4ad0f80859d/components/version/src/polylith/clj/core/version/interface.clj#L27[revision] is set to `SNAPSHOT`.
  - https://github.com/polyfy/polylith/blob/87aeb2ce093f31449827fb19d189e4ad0f80859d/components/version/src/polylith/clj/core/version/interface.clj#L28[snapshot] is set to `34`.
  - https://github.com/polyfy/polylith/blob/87aeb2ce093f31449827fb19d189e4ad0f80859d/components/version/src/polylith/clj/core/version/interface.clj#L40[date] is set to today's date (yyyy-mm-dd).
. Ensure the versions are correctly specified in `readme.adoc`:
  - `:snapshot-number:` is set to `34`.
  - `:snapshot-version:` is set to `0.2.20`.
  - `:stable-version:` is set to `0.2.19`.
. When adding a new doc page, update the _Doc updates_ section in `next-release.md`.
. Whenever the workspace structure changes:
  - update the xref:versions.adoc[Versions] table
  - update the code that migrates exported files in the https://github.com/polyfy/polylith/blob/f5da3d2e206182c7231cabf4207a7001f82508b4/components/ws-file-reader/src/polylith/clj/core/ws_file_reader/from_disk.clj#L11[ws-file-reader] component.
  - update next-release.md
. If a new attribute is added to _workspace.edn_
  - update all workspace.edn template files under scripts/sections
  - update the content of workspace.edn after "The workspace.edn file looks like:" in workspace.adoc.
. Check that `:template-data` in `workspace.edn` uses the latest version for `:clojure-ver` and `:shadow-cljs-ver`.
. Run `bb check` to check for reflection warnings and such.
  - If new bricks, add the source directory to the `:check` alias in `./deps.edn`.
. Execute `bb gen-all`
   - Compare the output with what's in git, and commit the changes if everything looks good.
. Verify that we have included everything in https://github.com/polyfy/polylith/blob/master/next-release.md[next-release.md].
. Commit and push your changes.
. If the next release is a stable release, build a xref:#local-cljdoc[local version] of Cljdoc:
  - Check that new content looks correct.
  - Verify that we have included everything in https://github.com/polyfy/polylith/blob/master/next-release.md[next-release.md].
  - Check that the badges at the top and the API at the bottom left are displayed correctly (most namespaces should begin with a `^:no-doc` tag, to exclude them from the API doc).
. Go to the https://github.com/polyfy/polylith[polylith repo] and prepare to merge the `snapshot-022034` branch into `master`, by clicking the "Compare & pull requests" button at the top.
If the https://app.circleci.com/pipelines/github/polyfy[circlci pipeline] is green, merge it into the `master` branch.
. When built, find newly built release under https://github.com/polyfy/polylith/releases[releases]
  - Edit and update it with "0.2.20-SNAPSHOT 34"
  - List included issues and other changes.
. Execute `git switch master` followed by `git pull` to get the latest from `master`.
. If the next release is a snapshot release, execute `git switch -c snapshot-022035`, otherwise follow the instructions for creating a stable release.

[#create-a-stable-release]
== Create a stable release

In this example, we want to create a `0.2.20` release out of a `0.2.20-SNAPSHOT 34` release.

Run all the tests:

[source,shell]
----
poly test :all
----

Announce in good time in the https://clojurians.slack.com/archives/C013B7MQHJQ[polylith channel] in Slack, that people should start testing current SNAPSHOT version.
Also mention that there will only be minor changes until release, such as updating the documentation. Wait a few days before you make the new release.

Make a `0.2.20` release:

. Execute `git switch master` followed by `git pull` to get the latest.
. Create the release branch by executing `git switch -c release-0220`.
. Update the `version` component and ensure that:
  - https://github.com/polyfy/polylith/blob/87aeb2ce093f31449827fb19d189e4ad0f80859d/components/version/src/polylith/clj/core/version/interface.clj#L24-L26[version] is set to `0.2.20`.
  - https://github.com/polyfy/polylith/blob/87aeb2ce093f31449827fb19d189e4ad0f80859d/components/version/src/polylith/clj/core/version/interface.clj#L27[revision] is set to `RELEASE`.
  - https://github.com/polyfy/polylith/blob/87aeb2ce093f31449827fb19d189e4ad0f80859d/components/version/src/polylith/clj/core/version/interface.clj#L28[snapshot] is set to `0`.
  - https://github.com/polyfy/polylith/blob/87aeb2ce093f31449827fb19d189e4ad0f80859d/components/version/src/polylith/clj/core/version/interface.clj#L40[date] is set to today's date (yyyy-mm-dd).
. Ensure the versions are correctly specified in `readme.adoc`:
  - `:snapshot-number:` is set to `0`.
  - `:snapshot-version:` is set to `0.2.20`.
  - `:stable-version:` is set to `0.2.20`.
. Whenever the workspace structure changes, remember to update the xref:versions.adoc[Versions] table, and also update the code that migrates exported files in the https://github.com/polyfy/polylith/blob/f5da3d2e206182c7231cabf4207a7001f82508b4/components/ws-file-reader/src/polylith/clj/core/ws_file_reader/from_disk.clj#L11[ws-file-reader] component.
. Ensure that `readme.adoc` lists the correct sponsors by cross-checking it against the https://github.com/sponsors/polyfy/dashboard/your_sponsors[actual] sponsors.
. Update the doc and its navigation:
  - If a page has been added to the link:../doc[doc] directory, also add it to link:/{docdir}/cljdoc.edn[cljdoc.edn] and execute https://github.com/polyfy/polylith/blob/205210dee83c7837be9546e12aa08707eecdd919/bases/nav-generator/src/polylith/clj/core/nav_generator/main.clj#L30[this] function to generate the doc navigation.
  - If a xref:blog-posts[blog post], xref:videos[video] or xref:high-level[high-level doc] page has been added, then update link:../components/doc/src/polylith/clj/core/doc/navigation/more.clj[more.clj].
  - If any doc content has been added, make sure to update corresponding examples in the doc, e.g. what xref:more[more] outputs.
. Search for occurrences of `:poly-version:` constants, and set the version to `0.2.20` wherever it appears (at the top of .adoc files).
. Commit.
. Execute `bb gen-all`
  - Compare the output with what's in git
  - Commit and push the changes if everything looks correct.
. Go to the https://github.com/polyfy/polylith[polylith repo] and prepare to merge the `release-0220` branch into `master`, by clicking the "Compare & pull requests" button at the top.
  - Add a comment indicating that this is release 0.2.20.
  - If the https://app.circleci.com/pipelines/github/polyfy[circlci pipeline] is green, merge it into the `master` branch.
    - List all issues and PRs with hashes in the commit to ensure they are properly linked.
  - Ensure that the https://cljdoc.org/d/polylith/clj-poly/0.2.20/doc/readme[poly-clj] documentation has been built.
. Update the https://github.com/polyfy/polylith/releases/tag/v0.2.20[release notes] for the 0.2.20 release:
  - Summarize the release in the introduction.
  - Copy the content from https://github.com/polyfy/polylith/blob/master/next-release.md[next-release.md] into the release notes.
. Update the https://github.com/polyfy/homebrew-polylith[Polylith Homebrew Tap].
. Execute `git switch master` followed by `git pull` to get the latest from master.
. Execute `git switch -c snapshot-022100` to create a first snapshot branch for the next release (here we imagine that the next release is 0.2.21).
. Update the version component:
  - Update version to 0.2.21 SNAPSHOT #0 (revision to SNAPSHOT, patch to 21, snapshot to 0)
. Update readme.adoc:
  - leave `:snapshot-number:` as 0
  - leave `:stable-version:` as 0.2.20
  - set `:snapshot-version:` to 0.2.21
. Update https://github.com/polyfy/polylith/blob/master/next-release.md[next-release.md]:
  - Change the heading to "Included since 0.2.20"
  - Clean everything (remove everything under each header)
. Create a `0.2.21-SNAPSHOT 0` release, see xref:#create-a-snapshot-release[make a snapshot release for instructions].
  - Add comment: 0.2.21-SNAPSHOT 0 (same as 0.2.20).
  - Check what is included under the tab "File Changed"
. Delete old `0.2.20-SNAPSHOT` releases.
. Announce in https://clojurians.slack.com/archives/C015AL9QYH1[#releases] if a minor release, or in https://clojurians.slack.com/archives/C06MAR553[#announcements] if a big release (in clojurians in Slack) by summarizing the most important changes + the included issues and PRs + add a link to the #polylith channel.
. Announce on social media
