= Git Hook

You can use https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks[git hooks] to have Git invoke custom scripts for specific Git events.

Some folks add a `commit-msg` hook to have Git automatically run the `poly` xref:commands.adoc#check[check] command to xref:validations.adoc[validate] their workspace on https://git-scm.com/docs/git-commit[git commit].
If the `poly check` fails, the `git commit` is aborted.

From your workspace root directory, you'd add an executable `./git/hooks/commit-msg` script, something like the following would work on macOS or Linux:

../git/hooks/commit-msg
[source,shell]
----
#!/usr/bin/env bash

set -eou pipefail

clojure -M:poly check color-mode:none
----

TIP: Don't forget to `chmod +x ./get/hooks/commit-msg`.

TIP: Client-side git hooks are developer-specific and not tracked by `git`.

WARNING: Failing hooks can be mysterious when committing from an IDE.
If the commit hook fails, the commit will fail, but you might not get a meaningful message as to why.

TIP: The example git hook script above invokes `poly` via the `:poly` alias.
For better performance, you might explore having your git hook script invoke xref:install.adoc[poly as a stand-alone AOT-compiled jar].