== Install as Clojure CLI Tool

If we are using a recent version of the https://clojure.org/releases/tools[Clojure CLI] -- 1.10.3.933 or later -- we can install _poly_ as a "tool":

[source,shell]
----
clojure -Ttools install io.github.polyfy/polylith '{:git/tag "v0.2.18" :deps/root "projects/poly"}' :as poly
----

An alternative is to give a sha, which allows us to use old versions or versions that hasn't been released yet, e.g.:

[source,shell]
----
clojure -Ttools install io.github.polyfy/polylith '{:git/sha "5f74c8b8675dbb091258165d327af3958716a247" :deps/root "projects/poly"}' :as poly
----

[Note]
====
Note: do not use the _install-latest_ option to `clojure -Ttools` as it does not support _:deps/root_.
====

Then we can invoke the poly tool using the CLI directly:

[source,shell]
----
clojure -Tpoly info loc true
----

Or start a poly shell, which uses the standard Polylith way of passing in arguments to commands:

[source,shell]
----
clojure -Tpoly
----

Installed versions can be listed with:

[source,shell]
----
clojure -Ttools list
----

...or the shorter (_clojure_ can often be replaced with _clj_):

[source,shell]
----
clj -Ttools list
----

We can get basic built-in help via the CLI's help machinery:

[source,shell]
----
clojure -A:deps -Tpoly help/doc
----

[Note]
====
NOTE: the command-line argument syntax for "tool" usage follows the CLI "exec args" format which is essentially Clojure's own keyword/value syntax (it's actually read as EDN).
====

How to use the _poly_ command as a tool is described in the xref:clojure-cli-tool.adoc[Clojure CLI Tool] section. The official documentation can be found https://clojure.org/reference/deps_and_cli#tool_install[here].
