= Install
:toc:

There are several ways to install the _poly_ tool, which determines how the _poly_ tool will be executed:

1. As a stand-alone command line tool, executed as a Java program, e.g. `poly help`:
- The _poly_ tool can be executed from any directory.
- A script named _poly_ is installed on your local disk and added to the system path, with a content like this: `java -jar poly.jar`

2. By the https://clojure.org/guides/deps_and_cli[Clojure CLI], e.g. `clojure -M:poly help`:
- The _poly_ tool can only be executed from inside a Polylith xref:workspace.adoc[workspace] directory (it uses the _:poly_ alias in _deps.edn_).
- Which version of the _poly_ tool to use can easily be selected by changing the SHA in _./deps.edn_.

3. As a https://clojure.org/reference/deps_and_cli#tool_install[Clojure CLI tool], e.g. `clojure -Tpoly help`:
- The _poly_ tool can be executed from any directory.
- Different versions of the _poly_ tool can easily be installed and switched to.
- It doesn't follow the _poly_ way of passing in arguments, which is described xref:clojure-cli-tool.adoc[here].

With this said, it's useful to install the tool both as a stand-alone command line tool, and any or both of the other two variants,
but it's mainly up to your preferences how you prefer to use the tool.

Now it's time to install the _poly_ tool, so please follow the installation instructions for your operating system of choice.

== Install on Mac

To use the _poly_ tool and to get access to all the features in tools.deps, make sure you have
https://clojure.org/guides/getting_started[CLI tools] and https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[git] installed.
If you install git for the first time, don't forget to set the
https://docs.github.com/en/github/using-git/setting-your-username-in-git[user] name and email.

To install the _poly_ command on Mac, execute:

[source,shell]
----
brew install polyfy/polylith/poly
----

If you get the error "openjdk-13.0.2.jdk could not be opened...", do this:

- Open MacOS _System Preferences_ > _Security & Privacy_ > _General_.
- Click Allow at the bottom for _openjdk-13.0.2.jdk_.
- Run `brew install polyfy/polylith/poly` again.

Verify the installation by executing `poly help`.

== Install on Linux

To use the _poly_ tool and to get access to all the features in tools.deps, make sure you have
https://clojure.org/guides/getting_started[CLI tools] and https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[git] installed.
If you install git for the first time, don't forget to set the
https://docs.github.com/en/github/using-git/setting-your-username-in-git[user] name and email.

To install the _poly_ command on Linux:

* Download the https://github.com/polyfy/polylith/releases/latest[latest release] of the poly jar,
e.g.: _poly-0.2.18.jar_.
* Create a directory, e.g. _/usr/local/polylith_, and copy the jar file to that directory.
* Create a file with the name _poly_ and put it in e.g. _/usr/local/bin_ with this content:

[source,shell]
----
#!/bin/sh

ARGS=""
while [ "$1" != "" ] ; do
 ARGS="$ARGS $1"
 shift
done

exec "/usr/bin/java" $JVM_OPTS "-jar" "/usr/local/polylith/poly-0.2.17-alpha.jar" $ARGS
----

* Make sure that:
- You point to the correct jar file.
- The path to _java_ is correct (can be verified with `which java`).
* If you choose _/usr/local/bin_, it was probably already on your path, otherwise you have to add it.
* Make it executable by executing `chmod +x poly`.

Verify the installation by executing `poly help`.

== Install on Windows

To use the _poly_ tool and to get access to all the features in tools.deps, make sure you have
https://clojure.org/guides/getting_started[CLI tools] and https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[git] installed.
If you install git for the first time, don't forget to set the
https://docs.github.com/en/github/using-git/setting-your-username-in-git[user] name and email.

=== Install clj

If you got this error when installing _clj_:

[source,shell]
----
clj : The 'clj' command was found in the module 'ClojureTools', but the module could not be loaded.
For more information, run 'Import-Module ClojureTools'.
----

...and if you followed the instruction and executed this:

[source,shell]
----
Import-Module ClojureTools
----

...and got this error:

[source,shell]
----
Import-Module : File C:\Users\Admin\Documents\WindowsPowerShell\Modules\ClojureTools\ClojureTools.psm1
cannot be loaded because running scripts is disabled on this system. For more information,
see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
----

...then try this:

[source,shell]
----
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
----

=== Install poly

* Download the https://github.com/polyfy/polylith/releases/latest[latest release] of the poly jar,
e.g. _poly-0.2.18.jar_.
* Create the _Polylith_ directory somewhere on your machine, e.g.
_C:\Program Files\Polylith_ and copy the jar file to that directory.
* Create the file _poly.bat_ with this content (make sure you point to the jar):

[source,shell]
----
@echo off
start /wait /b java %JAVA_OPTS% -jar "C:\Program Files\Polylith\poly-0.2.18.jar" %*
----

* Add _C:\Program Files\Polylith_ to the Windows _PATH_ environment variable.

Test the installation by typing _poly help_ from the command line.

====
NOTE: The xref:colors.adoc[coloring] of text is not supported on Windows.
====

== Install via nix

The _poly_ tool is available in the
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/misc/polylith/default.nix[nixpkgs] as well:

[source,shell]
----
nix-shell -p polylith
# or
nix-env -iA 'nixos.polylith'
----

== Install as Clojure CLI Tool

If we are using a recent version of the
https://clojure.org/releases/tools[Clojure CLI] -- 1.10.3.933 or later -- we can install _poly_ as a "tool":

[source,shell]
----
clojure -Ttools install io.github.polyfy/polylith '{:git/tag "v0.2.18" :deps/root "projects/poly"}' :as poly
----

An alternative is to give a sha, which allows us to use old versions or versions that hasn't been released yet, e.g.:

[source,shell]
----
clojure -Ttools install io.github.polyfy/polylith '{:git/sha "5f74c8b8675dbb091258165d327af3958716a247" :deps/root "projects/poly"}' :as poly
----

====
NOTE: do not use the _install-latest_ option to `clojure -Ttools` as it does not support _:deps/root_.
====

Then we can invoke the _poly_ tool using the CLI directly:

[source,shell]
----
clojure -Tpoly info loc true
----

Or start a poly shell, which uses the standard Polylith way of passing in arguments to commands (`clojure -Tpoly` will not work here):

[source,shell]
----
clojure -Tpoly shell
----

Installed versions can be listed with:

[source,shell]
----
clojure -Ttools list
----

...or the shorter (_clojure_ can often be replaced with _clj_):

[source,shell]
----
clj -Ttools list
----

We can get basic built-in help via the CLI's help machinery:

[source,shell]
----
clojure -A:deps -Tpoly help/doc
----

====
NOTE: the command-line argument syntax for "tool" usage follows the CLI "exec args" format which is essentially
Clojure's own keyword/value syntax (it's actually read as EDN).
====

How to use the _poly_ command as a tool is described in the xref:clojure-cli-tool.adoc[Clojure CLI Tool] section.
The official documentation can be found https://clojure.org/reference/deps_and_cli#tool_install[here].

== Use as dependency

An alternative way of executing the _poly_ tool is to specify it as a dependency, by giving a commit SHA.
To use it this way, add one of the following aliases to the _:aliases_ section in your _./deps.edn_:

* Via Clojars:

[source,clojure]
----
{
...
 :aliases   {:poly  {:extra-deps {polylith/clj-poly
                                  {:mvn/version "0.2.18"}}
                     :main-opts  ["-m" "polylith.clj.core.poly-cli.core"]}}
...
}
----

* Via GitHub:

[source,clojure]
----
{
...
 :aliases   {:poly  {:extra-deps {polylith/clj-poly
                                  {:git/url   "https://github.com/polyfy/polylith.git"
                                   :sha       "INSERT_LATEST_SHA_HERE"
                                   :deps/root "projects/poly"}}
                     :main-opts  ["-m" "polylith.clj.core.poly-cli.core"]}}
...
}
----

Replace _INSERT_LATEST_SHA_HERE_ with a https://github.com/polyfy/polylith/commits/master[commit SHA]
from the Polylith repository (e.g. the latest from the _master_ branch).

====
NOTE: The master branch can sometimes be ahead of the https://github.com/polyfy/polylith/releases[latest release].
Instead of waiting for the next version to be released, you can set the latest commited SHA from the
https://github.com/polyfy/polylith/commits/master[master branch], each time it updates in _./deps.edn_ (see the example above).
This works especially well if you also start a xref:shell[]] from the workspace root with `clojure -M:poly`.
====

Once we have added one of the aliases above, we can now use the _poly_ tool from the terminal:

[source,shell]
----
clojure -M:poly version
----

We will soon create our first xref:workspace.adoc[workspace] but before that is done, only the _version_, _help_,
and _create workspace_ commands will work.

== Polylith as a library
[#polylith-as-a-library]

If we are building tooling around Polylith, then we can use the https://clojars.org/polylith/clj-poly/versions[clj-poly]
library to get access to some of the funtionality that is built in to the _poly_ tool itself.

It exposes two interfaces:

* The https://github.com/polyfy/polylith/blob/master/components/api/src/polylith/clj/core/api/interface.clj[api] interface.

* The https://github.com/polyfy/polylith/blob/master/components/test-runner-contract/src/polylith/clj/core/test_runner_contract/interface.clj[test-runner-contract] interface.

Only these exposed functions are part of the public API. All other code is subject to change.

Since version 0.2.18 we only publish _clj-poly_ to Clojars and not the old _clj-api_ any more.

You can add _clj-poly_ as a dependency to a _:deps_ section in your _deps.edn_ file
(make sure to use the https://github.com/polyfy/polylith/releases[latest] release):

[source,shell]
----
polylith/clj-poly {:mvn/version "0.2.18"}
----

or

[source,shell]
----
polylith/clj-poly {:git/url   "https://github.com/polyfy/polylith.git"
:sha       "ecd2cf2ede81ecd4fbf82f21a075b103b6f2d2af"
:deps/root "projects/poly"}
----

...and remember to set the _:sha_ to an existing https://github.com/polyfy/polylith/commits/master[SHA].

== JVM options

If we want to add extra memory to the _poly_ tool or maybe specify where the configuration file for the logging is stored,
then we can set the _JVM_OPTS_ environment variable to do that, because _JVM_OPTS_ is also
https://github.com/polyfy/polylith/blob/9053b190d5f3b0680ac4fe5c5f1851f7c0d40830/build/resources/brew/exec#L22[passed in]
when executing the _poly_ command.

If we use the tools.deps CLI to execute the _poly_ command, e.g. `clojure -M:poly test`,
we can configure the logging in the _:poly_ alias in _./deps.edn_ for the project, e.g.:

[source,clojure]
----
{:aliases  {...
            :poly {...
                   :extra-deps {...
                                org.apache.logging.log4j/log4j-api {:mvn/version "2.20."}
                                org.apache.logging.log4j/log4j-slf4j-impl {:mvn/version "2.20.0"}}}}
----
