== Install on Linux

To use the poly tool and to get access to all the features in tools.deps, make sure you have https://clojure.org/guides/getting_started[CLI tools] and https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[git] installed. If you install git for the first time, don't forget to set the https://docs.github.com/en/github/using-git/setting-your-username-in-git[user] name and email.

To install the _poly_ command on Linux:

* Download the https://github.com/polyfy/polylith/releases/latest[latest release] of the _poly_ jar,
e.g. _poly-0.2.18.jar_.
* Create a directory, e.g. _/usr/local/polylith_ and copy the jar file to that directory.
* Create a file with the name _poly_ and put it in e.g. _/usr/local/bin_ with this content:

[source,shell]
----
#!/bin/sh

ARGS=""
while [ "$1" != "" ] ; do
 ARGS="$ARGS $1"
 shift
done

exec "/usr/bin/java" $JVM_OPTS "-jar" "/usr/local/polylith/poly-0.2.17-alpha.jar" $ARGS
----

* Make sure that:
- You point to the correct jar file.
- The path to _java_ is correct (can be verified with `which java`).
* If you choose _/usr/local/bin_, it was probably already on your path, otherwise you have to add it.
* Make it executable by executing `chmod +x poly`.

Verify the installation by executing `poly help`.
