= Introduction

This documentation aims to be a practical guide to this tool with lots of code examples.
We encourage you to follow the code examples and try it out yourself.
We will guide you through the steps of creating a workspace with projects composed of components, bases, and libraries
and how to work with them from the development environment and the interactive shell.

We will give a short introduction to tools.deps and how to use tools.build to create deployable artifacts.
We will show how git is used to tag the code and how it enables us to test and release the code incrementally.

We will show how profiles will help us work from a single development environment for maximum efficiency
and how dependencies and library usage can be displayed.

We will explain the value of components and how they bring context to our development experience,
which will help us build decoupled and scalable systems from day one.

Let's begin!


poly:
  version: 0.2.18-issue318-02
cljdoc:
  url: http://localhost:8000/d/polylith/clj-poly/0.2.18-issue318-02/doc

poly version: $poly-version
$cljdoc-url/readme[cljdoc-url readme]

START

ifdef::env-cljdoc[]
poly2:
  version: 0.2.18-issue318-02
cljdoc2:
  url: http://localhost:8000/d/polylith/clj-poly/0.2.18-issue318-02/doc

poly version: $poly2-version
$cljdoc2-url/readme[cljdoc-url readme]
endif::[]

END


ifdef::env-github[]
====
NOTE: With start from version 0.2.18, this _poly_ tool documentation lives together with the source code in the
link:../doc[doc] directory. A cljdoc based http://localhost:8000/d/polylith/clj-poly/0.2.18-issue318-02/doc/readme[documentation]
is then generated for each released version (the version is displayed at the top of the page) which we recommend you to use.
====
endif::[]
