= Introduction
:cljdoc-doc-url: https://cljdoc.org/d/polylith/clj-poly/CURRENT/doc

ifndef::env-cljdoc[]
TIP: For a richer experience, we recommend reading on {cljdoc-doc-url}/introduction[cljdoc].
endif::[]

This documentation is a practical guide to the `poly` tool.

We include many code examples.
They act as an ongoing tutorial as you read sequentially through the documentation.
We encourage you to follow the tutorial examples and try them out yourself.
For your convenience, we provide the end result link:/examples/doc-example[here].

We will guide you through the steps of creating a workspace with projects composed of components, bases, and libraries and how to work with them from the development environment and the interactive shell.

We will give a short introduction to tools.deps and how to use tools.build to create deployable artifacts.
We will explain how git is used to tag the code and how it enables us to test and release the code incrementally.

We will show how profiles will help us work from a single development environment for maximum efficiency and how dependencies and library usage can be displayed.

We will explain the value of components and how they bring context to our development experience, which will help us build decoupled and scalable systems from day one.

/Joakim Tengstrand

Let's begin!
