= Introduction
:cljdoc-doc-url: https://cljdoc.org/d/polylith/clj-poly/CURRENT/doc

ifndef::env-cljdoc[]
TIP: For a richer experience, we recommend reading on {cljdoc-doc-url}/introduction[cljdoc].
endif::[]

This documentation offers a practical guide to using the Polylith tool.
Our goal is to teach you the value of components and how they bring context to the development experience.
We want to empower you to build decoupled and scalable systems from day one.

We have included many code examples.
We strongly encourage you to try them out!

You will learn how to:

* Create a workspace with projects composed of components, bases, and libraries.
* Use the development environment and the interactive shell.
* Use tools.deps and then tools.build to create deployable artifacts.

We will explain how:

* We leverage git tagging to support incremental tests and releases.
* Profiles allow us to work efficiently from a single development environment.
* To easily understand your dependency and library usage.

Let's begin!
