= Templates
:toc:

Whenever you run the xref:commands.adoc#create[create command],
Polylith uses template files to generate the desired files in
the new component, base, project, or workspace.

Polylith has a default set of template files for this but you
can override some or all of them on a per-project or global (user)
level.

Each template can use a number of variable substitutions (listed
below), using `{{var-name}}` for the placeholder to be replaced.
The specific variables provided for each template are shown in the
various `create` sections below.

Because Polylith uses https://github.com/yogthos/Selmer[Selmer]
for rendering the templates, you can also use any of the built-in
filters and tags in your templates. For example, you might want
to add a copyright notice at the top of your source files:

[source,text]
----
;; copyright (c) {% now "yyyy" %} acme inc, all rights reserved

(ns {{interface-ns}}
  (:require [{{impl-ns}} :as impl]))
----

Since you can override the `development` and projects' `deps.edn` files,
you can provide your own default dependencies, such as testing libraries,
and you can override how test files are rendered to `:require` those
testing libraries and provide default tests using that style.

The full set of template files is:

[source,text]
----
templates
├── .gitignore
├── bases
│   ├── deps.edn
│   ├── main.clj
│   ├── package.json
│   └── test.clj
├── components
│   ├── deps.edn
│   ├── impl.clj
│   ├── interface.clj
│   ├── package.json
│   └── test.clj
├── deps.edn
├── projects
│   ├── deps.edn
│   └── package.json
├── package.json
├── readme.md
└── workspace.edn
----

`templates/components/impl.clj` is optional (and has no default version).

The per-project templates should be added to the `.polylith` folder
within the project, e.g., `<project>/.polylith/templates/components/interface.clj`

The per-user templates to should be added to the `.config/polylith` folder
in your home directory, e.g., `$HOME/.config/polylith/templates/workspace.edn`

For each template needed by the `poly create` command, the per-project one
is used if present, else the per-user one is used if present, else Polylith's
internal default version.

== create workspace

This command uses the following template files to generate parts of the new workspace:

* `templates/.gitignore` -> the top-level `.gitignore` file
* `templates/deps.edn` -> the top-level `deps.edn` file
* `templates/package.json` -> the top-level `package.json` file
* `templates/readme.md` -> the top-level `readme.md` file
* `templates/workspace.edn` -> the top-level `workspace.edn` file

For all these templates, the following variables are provided:

* `{{clojure-ver}}` -- the version of Clojure to use; e.g. `"1.12.2"`
* `{{:ws-dialects}}` -- the dialects, e.g. `["clj" "cljs"]` (from the xref:commands.adoc#create-workspace[create workspace] command). Set to `["clj"]` if not provided.
* `{{maven-ver}}` -- the default version of Polylith to use
* `{{:shadow-cljs-ver}}` - the version of shadow-cljs to use; e.g. `"^3.2.0"`
* `{{top-ns}}` -- the top namespace name (from the xref:commands.adoc#create-workspace[create workspace] command)
* `{{ws-name}}` -- the name of the workspace (from the xref:commands.adoc#create-workspace[create workspace] command)

NOTE: a `package.json` file is created only if `dialects´ includes `cljs` (e.g., ´dialects:cljs´ or ´dialects:clj:cljs´).

== create component

This command uses the following template files to generate the new component:

* `templates/components/deps.edn` -> the new component's `deps.edn` file
** `{{dialect}}` -- the dialect, e.g. "cljs" (from the xref:commands.adoc#create-component[create component] command)
* `templates/components/interface.clj` -> the new component's interface source file (based on the `:interface-ns` setting in `workspace.edn` etc)
** `{{dialect}}` -- the dialect, e.g. "cljs" (from the xref:commands.adoc#create-component[create component] command)
** `{{interface-ns}}` -- the interface namespace (from the `create component` command)
** `{{impl-ns}}` -- the `impl.clj` namespace name (derived from the interface name)
* if present, `templates/components/impl.clj` -> the new component's `impl.clj` source file
** `{{dialect}}` -- the dialect, e.g. "cljs" (from the xref:commands.adoc#create-component[create component] command)
** `{{interface-ns}}` -- the interface namespace (from the xref:commands.adoc#create-component[create component] command)
** `{{impl-ns}}` -- the `impl.clj` namespace name (derived from the interface name)
* `templates/components/package.json` -> the new component's `package.json` file
** `{{dialect}}` -- the dialect, e.g. "cljs" (from the xref:commands.adoc#create-component[create component] command)
** `{{brick-name}}` -- the name of the component (from the xref:commands.adoc#create-component[create component] command)
** `{{shadow-cljs-ver}}` -- the version of shadow-cljs to use; e.g. `"^3.2.0"`
* `templates/components/test.clj` -> the new component's interface test file
** `{{dialect}}` -- the dialect, e.g. "cljs" (from the xref:commands.adoc#create-component[create component] command)
** `{{test-ns}}` -- the namespace of the new test file
** `{{src-ns}}` -- the namespace of the new source file -- the interface namespace
** `{{alias}}` -- an alias that can be used for the source file in `:require`

NOTE: The `package.json` file is created only when `dialect:cljs` is passed to the command.

== create base

This command uses the following template files to generate the new base:

* `templates/bases/deps.edn` -> the new base's `deps.edn` file
** `{{dialect}}` -- the dialect, e.g. "cljs" (from the xref:commands.adoc#create-base[create base] command)
* `templates/bases/main.clj` -> the new base's `core.clj` source file
** `{{dialect}}` -- the dialect, e.g. "cljs" (from the xref:commands.adoc#create-base[create base] command)
** `{{main-ns}}` -- the core namespace
* `templates/bases/package.json` -> the new base's `package.json` file
** `{{dialect}}` -- the dialect, e.g. "cljs" (from the xref:commands.adoc#create-base[create base] command)
** `{{brick-name}}` -- the name of the base (from the xref:commands.adoc#create-base[create base] command)
** `{{shadow-cljs-ver}}` -- the version of shadow-cljs to use; e.g. `"^3.2.0"`
* `templates/bases/test.clj` -> the new base's interface test file
** `{{dialect}}` -- the dialect, e.g. "cljs" (from the xref:commands.adoc#create-base[create base] command)
** `{{test-ns}}` -- the namespace of the new test file
** `{{src-ns}}` -- the namespace of the new source file -- the `core` namespace
** `{{alias}}` -- an alias that can be used for the source file in `:require`

NOTE: The `package.json` file is created only when `dialect:cljs` is passed to the command.

== create project

This command uses the following template files to generate the new project:

* `templates/projects/deps.edn` -> the project's `deps.edn` file
* `templates/projects/package.json` -> the project's `package.json` file

For these templates, the following variables are provided:

* `{{dialect}}` -- the dialect, e.g. "cljs" (from the xref:commands.adoc#create-project[create project] command)
* `{{clojure-ver}}` -- the default version of Clojure to use; currently `"1.12.0"`
* `{{project-name}}` -- the name of the project (from the xref:commands.adoc#create-project[create project] command)
* `{{shadow-cljs-ver}}` -- the version of shadow-cljs to use; e.g. `"^3.2.0"`

NOTE: The `package.json` file is created only when `dialect:cljs` is passed to the command.
