= Test Runners
:toc:
:cljdoc-api-url: https://cljdoc.org/d/polylith/clj-poly/CURRENT/api

The _poly_ tool started to support test runners since version 0.2.15.
There is a https://github.com/polyfy/polylith/blob/9053b190d5f3b0680ac4fe5c5f1851f7c0d40830/components/clojure-test-test-runner/src/polylith/clj/core/clojure_test_test_runner/core.clj#L85-L99[default test runner]
which uses Clojure's default testing framework to run the tests as an in-process test runner.

It's possible to create and use our own custom test runner(s) with the _poly_ tool.
There are two types of test runners; in-process and external.
Polylith provides us with two protocols, _TestRunner_ and _ExternalTestRunner_.
We can use them to easily plug our custom test runner(s) into the _poly_ tool.

== In-Process Test Runner

As you already learned, the _poly_ tool can run our tests incrementally.
It creates an isolated classloader for each project and runs our tests within that classloader.
The idea is to speed up the execution time by running the tests in the same process with minimal overhead.

The default in-process test runner and custom in-process test runners use the isolated classloader approach we just described.
The _poly_ tool will figure out which bricks and projects are affected, calculate the classpath for each project,
create an isolated classloader, and pass it to the test runner for execution.

== External Test Runner

The alternative to the in-process isolated classloader approach is to execute each project's tests in a separate external Java subprocess.
The advantage of this approach is that you have complete control of the test execution,
and the memory is released after each project.
If you have issues with the in-process approach, then this type of test runner is the right way to go.

An external test runner will use external Java subprocesses to run the tests.
The _poly_ tool will still figure out the changed bricks and projects and calculate the classpath for each project.
However, the external test runner will create a runtime and run the tests.
Another difference is that the _poly_ tool will not run the setup and teardown functions for the tests.

====
IMPORTANT: The external test runner must run setup and teardown functions within the external process it creates.
The _poly_ tool will not run them for external test runners.
====

== In-process vs. External Test Runner

|===
| Aspect | In-Proces Test Runner | External Test Runner

| Context | Isolated project context | Isolated project context
| Approach | Isolated in-process classloaders | Isolated Java subprocesses
| Speed | Fast | Some overhead per project
| Memory usage | Memory is released when the whole test run has finished | Memory is released after each project's test run
| Setup & Teardown | Handled by the _poly_ tool | Handled by the test runner
| Special arguments | _class-loader_, _eval-in-project_ | _process-ns_
| Additional functions | _N/A_ | _external-process-namespace_
|===

== TestRunner Protocol

You can find the _TestRunner_ protocol link:{cljdoc-api-url}/polylith.clj.core.test-runner-contract.interface#TestRunner[here].

== ExternalTestRunnerProtocol

You can find the _ExternalTestRunner_ protocol link:{cljdoc-api-url}/polylith.clj.core.test-runner-contract.interface#ExternalTestRunner[here].

== Implement Your Own Test Runner

To implement your custom test runner,
create a single-arity constructor function that reifies the _TestRunner_ protocol.
Optionally, you can also reify the _ExternalTestRunner_ protocol if you want to make an external test runner.

[source,clojure]
----
(ns se.example.example-test-runner)

...

(defn create [{:keys [workspace project test-settings is-verbose color-mode changes]}]
  ...

  (reify
    test-runner-contract/TestRunner
    (test-runner-name [this] ...)

    (test-sources-present? [this] ...)

    (tests-present? [this runner-opts] ...)

    (run-tests [this runner-opts] ...)

    ; Optional, only if you want an external test runner
    test-runner-contract/ExternalTestRunner
    (external-process-namespace [this] ...)))
----

The _poly_ tool will call your constructor function to get an instance of your test runner.
The constructor function will receive a map as the single argument. This map contains the following:

|===
| Map key | Description

| _:workspace_ | The workspace map. This map contains _:user-input_ which can be used to receive additional parameters for runtime configuration.
| _:project_ | A map that contains the details of the project that is currently being tested.
| _:test-settings_ | Test settings for the project that is currently being tested. This information is extracted from the _workspace.edn_.
| _:is-verbose_ | A boolean indicates if we are running in verbose mode or not.
| _:color-mode_ | The color mode that the _poly_ tool is currently running with.
| _:changes_ | A map of changes since the last stable point in time.
|===

== Use a Test Runner

To use a test runner in your workspace, you have to add it to the classpath that you are running the _poly_ tool to run the tests.
An ideal place to do it is the _:poly_ alias in your workspace _deps.edn_ file:

[source,clojure]
----
{:aliases
 {:poly
  {:extra-deps
   {polylith/clj-poly
    {:mvn/version "INSERT_LATEST_VERSION_HERE"}

    se.example/example-test-runner
    {:git/url   "https://github.com/my-company/example-test-runner"
     :git/sha   "INSERT_COMMIT_SHA_HERE"
     :deps/root "projects/example-test-runner"}}}}}
----

====
NOTE: The example above assumes that you use a test runner from a GitHub repository as a git dependency.
You can also have your custom test runner within the same Polylith workspace and depend on it via _:local/root_.
====

Once you have your test runner in the classpath,
you can add it to your workspace configuration so that the _poly_ tool can use it instead of the default test runner.
You can add global test runners,
which the _poly_ tool will use for every project unless the project-specific test configuration overrides it.
To add a global test configuration, add a map with the _:test_ key in your _workspace.edn_ file:

[source,clojure]
----
{...
 ; Global test configuration, used as default for every project.
 :test     {:create-test-runner [se.example.example-test-runner/create]}

 ; Project specific configurations
 :projects {"foo" {:alias "foo"}
            "bar" {:alias "barr"}
            "baz" {:alias "baz"}}}
----

====
NOTE: You can specify more than one test runner. In that case, all the test runners will run for the project one after another.
====

You can also define test runners per project.
The test runners specified for the project will be used instead of the global test runner if any.
You can add a _:test_ key in the project's configuration to select project-specific test runners:

[source,clojure]
----
{...
 ; Global test configuration, used as default for every project.
 :test     {:create-test-runner [se.example.example-test-runner/create]}

 ; Project specific configurations
 :projects {"foo" {:alias "foo"
                   ; Use another test runner only for this project
                   :test  {:create-test-runner [se.example.another-test-runner/create]}}

            "bar" {:alias "bar"
                   ; Use the default test runner instead of the global
                   :test  {:create-test-runner [:default]}}

            "baz" {:alias "bz"
                   ; Use both default and the example test runner for this project
                   :test {:create-test-runner [:default
                                               se.example.example-test-runner/create]}}}}
----

== Test Runners from the Community

The default test runner works fine in most cases and is simple and fast.
In some circumstances, using the same classloader for all your tests in the workspace doesn't give enough isolation.
In this case, the External Test Runner is a good choice.
If you switch to the Kaocha Test Runner, you will get more options in how to run your tests.

== Kaocha Test Runner

A simple https://github.com/lambdaisland/kaocha/[Kaocha]-based test runner implementation for Polylith.

*Repository*: https://github.com/imrekoszo/polylith-kaocha[imrekoszo/polylith-kaocha]

*Author*: https://github.com/imrekoszo[@imrekoszo]

*License*: MIT


== External Test Runner

An external (subprocess) test runner for Polylith. Avoids classloader, daemon thread, and memory usage issues
by running tests in a subprocess with only Clojure itself as a dependency.

*Repository*: https://github.com/seancorfield/polylith-external-test-runner[seancorfield/polylith-external-test-runner]

*Author*: https://github.com/seancorfield[@seancorfield]

*License*: Apache-2.0
