= Upgrade
:toc:
:poly-version: 0.3.32

If the `poly` tool has been xref:install.adoc[installed], it can be upgraded.

Polylith's releases are found and described on our link:https://github.com/polyfy/polylith/releases[releases page].
We document our release strategy in detail xref:polylith-ci-setup.adoc#release[here].

== Stand-alone macOS

Use standard brew package upgrade techniques.
For example:

[source,shell]
----
brew upgrade poly
----

Or, optionally, specify the tap:

[source,shell]
----
brew upgrade polyfy/polylith/poly
----

== Stand-alone Linux

1. Download the https://github.com/polyfy/polylith/releases/latest[latest release], e.g. `poly-{poly-version}.jar`.
2. Update the `poly` shell script you created during xref:install.adoc#install-on-linux[installation] to reference the new jar.

== Stand-alone Windows

1. Download the https://github.com/polyfy/polylith/releases/latest[latest release], e.g. `poly-{poly-version}.jar`.
2. Update the `poly.bat` file you created during xref:install.adoc#install-on-windows[installation] to reference the new jar.

== Stand-alone Nix

Use standard Nix upgrade techniques.
For example:

[source,shell]
----
nix-channel --update
----

Followed by:
[source,shell]
----
nix-env -u polylith
----

== As Dependency

Update your `polylith/clj-poly` dependency in your `./deps.edn` to the current version.