== Use as dependency

An alternative way of executing the _poly_ tool is to specify it as a dependency, by giving a commit SHA. To use it this way, add one of the following aliases to the _:aliases_ section in your _./deps.edn_:

* Via Clojars:

[source,clojure]
----
{
...
 :aliases   {:poly  {:extra-deps {polylith/clj-poly
                                  {:mvn/version "0.2.18"}}
                     :main-opts  ["-m" "polylith.clj.core.poly-cli.core"]}}
...
}
----

* Via GitHub:

[source,clojure]
----
{
...
 :aliases   {:poly  {:extra-deps {polylith/clj-poly
                                  {:git/url   "https://github.com/polyfy/polylith.git"
                                   :sha       "INSERT_LATEST_SHA_HERE"
                                   :deps/root "projects/poly"}}
                     :main-opts  ["-m" "polylith.clj.core.poly-cli.core"]}}
...
}
----

Replace _INSERT_LATEST_SHA_HERE_ with a https://github.com/polyfy/polylith/commits/master[commit SHA] from the Polylith repository (e.g. the latest).

[Note]
====
NOTE: The master branch can sometimes be ahead of the https://github.com/polyfy/polylith/releases[latest release]. Instead of waiting for the next version to be released, you can set the latest commited SHA from the https://github.com/polyfy/polylith/commits/master[master branch] each time it updates in _./deps.edn_ (see the example above).
This works especially well if you also start a shell from the workspace root with `clojure -M:poly`.
====

Once we have added one of the aliases above, we can now use the poly tool from the terminal:

[source,shell]
----
clojure -M:poly version
----

We will soon create our first _workspace_ but before that is done, only the _version_, _help_, and _create workspace_ commands will work.
