= Workspace

The workspace directory is the place where all our code and most of the xref:configuration.adoc[configuration] lives.

Let’s start by creating the example workspace with the top namespace _se.example_
by using the xref:commands.adoc#create-workspace[create workspace] command.

Make sure you execute the command outside a git repository:

[source,shell]
----
poly create workspace name:example top-ns:se.example :commit
----

This will create a workspace in the _main_ branch. By giving _branch:BRANCH-NAME_ the workspace can be created in a different branch, e.g.:

[source,shell]
----
poly create workspace name:example top-ns:se.example branch:master :commit
----

The workspace directory structure will end up like this:

[source,shell]
----
example                # workspace dir
├── .git               # git repository dir
├── .gitignore         # ignored files and dirs in git
├── .vscode
│   └── settings.json  # configuration for Calva
├── bases              # bases dir
├── components         # components dir
├── deps.edn           # development config file
├── development
│   └── src            # development specific code
├── logo.png           # polylith logo
├── projects           # projects dir
├── readme.md          # documentation
└── workspace.edn      # workspace config file
----

The directory structure is designed for quick navigation and ease of use. It helps us to understand and find all
our service-level building blocks, which lets us reason about the system at a higher level.

Each top-level directory contains a specific type of Polylith concept:

* A xref:base.adoc[base] is a building block that exposes a public API to external systems.

* A xref:component.adoc[component] is a building block for encapsulating a specific domain or part of the system.

* A xref:project.adoc[project] specifies a deployable artifact and what components, bases, and libraries it contains.

* The xref:development.adoc[development] project (_development_ + _deps.edn_) is used to work with the code in one place.

This structure gives a consistent shape to all Polylith projects and ensures that both new developers and veterans
can quickly understand and start working with systems that are new to them.
We think you will soon be addicted to the power and simplicity the Polylith structure gives to your projects!

The _bases_, _components_ and _projects_ directories also contain a _.keep_ file,
which is added to prevent git from deleting these directories, and can be deleted as soon as we add something to them.

The _workspace.edn_ file looks like this:

[source,shell]
----
{:top-namespace "se.example"
 :interface-ns "interface"
 :default-profile-name "default"
 :compact-views #{}
 :vcs {:name "git"
       :auto-add false}
 :tag-patterns {:stable "stable-*"
                :release "v[0-9]*"}
 :projects {"development" {:alias "dev"}}}
----

...and _deps.edn_ like this:

[source,shell]
----
{:aliases  {:dev {:extra-paths ["development/src"]
                  :extra-deps {org.clojure/clojure {:mvn/version "1.11.1"}}}

            :test {:extra-paths []}

            :poly {:main-opts ["-m" "polylith.clj.core.poly-cli.core"]
                   :extra-deps {polyfy/polylith
                                {:git/url   "https://github.com/polyfy/polylith"
                                 :sha       "1209a81e6b8f70987050d65d106e99d1a902969a"
                                 :deps/root "projects/poly"}}}}}
----

If all went well, the `poly` tool managed to set the latest sha for the _:poly_ alias by taking it from the
https://github.com/polyfy/polylith/commits/master[master] branch in this repository.
We can instruct it to go and get it by passing in _:latest-sha_:

[source,shell]
----
cd example
poly ws get:settings:vcs:polylith :latest-sha
----

The output will look something like this:

[source,shell]
----
{:branch "master",
 :latest-sha "887e4237cec8f42eaa15be3501f134732602bb41",
 :repo "https://github.com/polyfy/polylith.git"}
----

The _:latest-sha_ argument will tell the tool to go out and find the latest SHA from the Polylith repo
and populate the _:latest-sha_ attribute in the xref:workspace-structure.adoc[workspace structure],
which would otherwise not be set.

If you wonder how the _ws_ command works or what all the settings are for, be patient, everything will soon be covered in detail.

== Existing git repository

A Polylith workspace can also be created inside an existing git repo. When we do that, we have two alternatives.
Either we create the workspace directly at the root of the git repository (without giving a name) by executing e.g.:

[source,shell]
----
cd my-git-repo-dir
poly create workspace top-ns:com.mycompany
----

[source,shell]
----
my-git-repo-dir
├── bases
├── components
├── deps.edn
├── development
├── projects
└── workspace.edn
----

...or we put the workspace in a directory under the git repository by executing e.g.:

[source,shell]
----
cd my-git-repo-dir
poly create workspace name:my-workspace top-ns:com.mycompany
----

[source,shell]
----
my-git-repo-dir
└── my-workspace
    ├── bases
    ├── components
    ├── deps.edn
    ├── development
    ├── projects
    └── workspace.edn
----

To execute a command, we need to be at the root of the workspace, e.g.:

[source,shell]
----
cd my-workspace
poly info
----
