(ns polylith.clj.core.help.info
  (:require [polylith.clj.core.help.shared :as shared]
            [polylith.clj.core.util.interface.color :as color]))

(defn help-text [color-mode]
  (str "  Shows workspace information.\n"
       "\n"
       "  poly info [ARGS]\n"
       "\n"
       "  Here is an example output from this command:\n"
       "\n"
       "    stable since: " (color/grey color-mode "dec73ec | stable-lisa\n")
       "\n"
       "    " (color/environment "environments:" color-mode) " 2   " (color/interface "interfaces:" color-mode) " 3\n"
       "    " (color/base "bases:" color-mode) "        1   " (color/component "components:" color-mode) " 4\n"
       "\n"
       "    active profiles: " (color/profile "default" color-mode) "\n"
       "\n"
       "    environment   alias  source   " (color/profile "default  admin" color-mode) "\n"
       "    ---------------------------   --------------\n"
       "    " (color/environment "command-line  cl      ---       --      --" color-mode) "\n"
       "    " (color/environment "development   dev     x--       --      --" color-mode) "\n"
       "\n"
       "    interface  brick    " (color/environment "cl    dev  admin\n" color-mode)
       "    -----------------   ---   ----------\n"
       "    " (color/interface "payer" color-mode) "      " (color/component "payer" color-mode) "    " (color/environment "x--   xx-   --" color-mode) "\n"
       "    " (color/interface "user" color-mode) "       " (color/component "admin" color-mode) "    " (color/environment "x--   ---   xx" color-mode) "\n"
       "    " (color/interface "user" color-mode) "       " (color/component "user" color-mode) " *   " (color/environment "---   xx-   --" color-mode) "\n"
       "    " (color/interface "util" color-mode) "       " (color/component "util" color-mode) "     " (color/environment "x--   xx-   --" color-mode) "\n"
       "    -          " (color/base "cli" color-mode) "      " (color/environment "x--   xx-   --" color-mode) "\n"
       "\n"
       "  Let's go through each section:\n"
       "\n"
       "  1. stable since: " (color/grey color-mode "dec73ec | stable-lisa\n")
       "\n"
       "     This shows the first commit or the most recent commit marked as stable,\n"
       "     plus the name of the tag. More information can be found in the 'diff' command help.\n"
       "\n"
       "  2. " (color/environment "environments:" color-mode) " 2   " (color/interface "interfaces:" color-mode) " 3\n"
       "     " (color/base "bases:" color-mode) "        1   " (color/component "components:" color-mode) " 4\n"
       "\n"
       "     Shows how many " (color/environment "environments" color-mode) ", " (color/base "bases" color-mode) ", " (color/component "components" color-mode) " and " (color/interface "interfaces" color-mode) " there are in the workspace.\n"
       "\n"
       "  3. active profiles: " (color/profile "default" color-mode) "\n"
       "\n"
       "     Shows the names of active profiles. Those paths are merged into the " (color/environment "development" color-mode) "\n"
       "     environment. A profiles is an aliase in ./deps.edn that starts with a " (color/purple color-mode "+") ".\n"
       "     If no profile is selected, the " (color/profile "default" color-mode) " will be selected for you.\n"
       "     Active profile(s) can be selected by passing them in by name, e.g.:\n"
       "       poly info +admin\n"
       "\n"
       "  4. environment   alias  source   " (color/profile "default  admin" color-mode) "\n"
       "     ---------------------------   --------------\n"
       "     " (color/environment "command-line  cl      ---       --      --" color-mode) "\n"
       "     " (color/environment "development   dev     x--       --      --" color-mode) "\n"
       "\n"
       "    This table lists all environments. The 'environment' column shows the name of the\n"
       "    environments, which are the directory names under the 'environments' directory,\n"
       "    except for 'development' that stores its code under the 'development' directory.\n"
       "    The 'deps.edn' config files are stored under each environment, or at the root for dev.\n"
       "\n"
       "    Aliases are configured in " (color/purple color-mode ":env->alias") " in ./deps.edn.\n"
       "\n"
       "    The 'source' column has three x/- flags with different meaning:\n"
       "      x--  The environment has a 'src' directory, e.g. 'environments/command-line/src'.\n"
       "      -x-  The environment has a 'test' directory, e.g. 'environments/command-line/test'.\n"
       "      --x  The environment tests (its own) are marked for execution.\n"
       "\n"
       "    To show the 'resources' directory, also pass in :r or :resources, e.g. 'poly info :r':\n"
       "      x---  The environment has a 'src' directory, e.g. 'environments/command-line/src'.\n"
       "      -x--  The environment has a 'resources' directory, e.g. 'environments/command-line/resources'.\n"
       "      --x-  The environment has a 'test' directory, e.g. 'environments/command-line/test'.\n"
       "      ---x  The environment tests (its own) are marked for execution.\n"
       "\n"
       "    The last two columns are the profiles:\n"
       "      x-  The profile contains a path to the 'src' directory, e.g. 'environments/command-line/src'.\n"
       "      -x  The profile contains a path to the 'test' directory, e.g. 'environments/command-line/test'.\n"
       "\n"
       "    If also passing in :r or :resources, e.g. 'poly info +r':\n"
       "      x--  The profile contains a path to the 'src' directory, e.g. 'environments/command-line/src'.\n"
       "      -x-  The profile contains a path to the 'resources' directory, e.g. 'environments/command-line/resources'.\n"
       "      --x  The profile contains a path to the 'test' directory, e.g. 'environments/command-line/test'.\n"
       "\n"
       "  5. interface  brick    " (color/environment "cl    dev  admin\n" color-mode)
       "     -----------------   ---   ----------\n"
       "     " (color/interface "payer" color-mode) "      " (color/component "payer" color-mode) "    " (color/environment "x--   xx-   --" color-mode) "\n"
       "     " (color/interface "user" color-mode) "       " (color/component "admin" color-mode) "    " (color/environment "x--   ---   xx" color-mode) "\n"
       "     " (color/interface "user" color-mode) "       " (color/component "user" color-mode) " *   " (color/environment "---   xx-   --" color-mode) "\n"
       "     " (color/interface "util" color-mode) "       " (color/component "util" color-mode) "     " (color/environment "x--   xx-   --" color-mode) "\n"
       "     -          " (color/base "cli" color-mode) "      " (color/environment "x--   xx-   --" color-mode) "\n"
       "\n"
       "    This table lists all bricks and in which environments and profiles they are added to.\n"
       "\n"
       "    The 'interface' column shows what " (color/interface "interface" color-mode) " the component has. The name is the first\n"
       "    namespace after the component name, e.g.: " (shared/component-ns "interface" "user" color-mode) ".\n"
       "\n"
       "    The 'brick' column shows the name of the brick. In " (color/component "green" color-mode) " if a component or " (color/base "blue" color-mode) " if a base" ".\n"
       "    Each component lives in a directory under the 'components' directory and each base lives\n"
       "    under the 'bases' directory. If any file for a brick has changed since the last stable\n"
       "    point in time, it will be marked with an asterisk, * (" (color/component "user" color-mode) " in this example).\n"
       "    The changed files can be listed by executing 'poly diff'.\n"
       "\n"
       "    The next " (color/environment "cl" color-mode) " column is the " (color/environment "command-line" color-mode) " environment that lives under the 'environments' directory.\n"
       "    Each line in this column says whether a brick is included in the environment or not.\n"
       "\n"
       "    The flags mean:\n"
       "      x--  The environment contains a path to the 'src' directory, e.g. 'components/user/src'.\n"
       "      -x-  The environment contains a path to the 'test' directory, e.g. 'components/user/test'.\n"
       "      --x  The brick is marked to be executed from this environment.\n"
       "\n"
       "    If :r or :resources is also passed in:\n"
       "      x---  The environment contains a path to the 'src' directory, e.g. 'components/user/src'.\n"
       "      -x--  The environment contains a path to the 'resources' directory, e.g. 'components/user/resources'.\n"
       "      --x-  The environment contains a path to the 'test' directory, e.g. 'components/user/test'.\n"
       "      ---x  The brick is marked to be executed from this environment.\n"
       "\n"
       "    The next group of columns, " (color/environment "dev admin" color-mode) ", is the development environment with its profiles.\n"
       "    If passing in a plus with 'poly info +' then it will also show the " (color/profile "default" color-mode) " profile.\n"
       "    The flags for the " (color/environment "dev" color-mode) " environment works the same as for " (color/environment "cl" color-mode) ".\n"
       "\n"
       "    The flags for the " (color/profile "admin" color-mode) " profile means:\n"
       "      x-  The profile contains a path to the 'src' directory, e.g. 'components/user/src'.\n"
       "      -x  The profile contains a path to the 'test' directory, e.g. 'components/user/test'.\n"
       "\n"
       "    If :r or :resources is also passed in:\n"
       "      x--  The profile contains a path to the 'src' directory, e.g. 'components/user/src'.\n"
       "      -x-  The profile contains a path to the 'resources' directory, e.g. 'components/user/resources'.\n"
       "      --x  The profile contains a path to the 'test' directory, e.g. 'components/user/test'.\n"
       "\n"
       "  It's not enough that a path has been added to an environment to show an 'x', the file or directory\n"
       "  must also exist.\n"
       "\n"
       "  To see what tests that will be executed, arguments that are used to run the tests can also be\n"
       "  passed in, see 'test' command help."
       "\n"
       "  If any warnings or errors was found in the workspace, they are listed at the end,\n"
       "  see the 'check' command help for a complete list of validations.\n"))

(defn print-help [color-mode]
  (println (help-text color-mode)))
