(ns polylith.clj.core.doc.interface
  (:require [polylith.clj.core.doc.core :as core]))

(defn open-doc [cmd command other page ws]
  (core/open-doc cmd command other page ws))

(def command-pages {"check" [],
                    "create" [],
                    "create-base" [],
                    "create-component" [],
                    "create-project" [],
                    "create-workspace" [],
                    "deps" [],
                    "deps-brick" [],
                    "deps-project" [],
                    "deps-project-brick" [],
                    "deps-workspace" [],
                    "diff" [],
                    "info" [],
                    "libs" [],
                    "migrate" [],
                    "overview" [],
                    "shell" [],
                    "switch-ws" [],
                    "tap" [],
                    "test" [],
                    "ws" []})

(def other-urls {"realworld" []})

(def pages {"base" {},
            "build" {},
            "clojure-cli-tool" {},
            "colors" {},
            "component" {},
            "configuration" {},
            "context" {},
            "continuous-integration" {},
            "dependencies" {},
            "development" {},
            "example-systems" {},
            "explore-the-workspace" {},
            "flags" {},
            "git" {},
            "git-hooks" {},
            "install" {},
            "interface" {},
            "introduction" {},
            "libraries" {},
            "migrate" {},
            "naming" {},
            "parameters" {},
            "polyx" {},
            "profile" {},
            "project" {},
            "readme" {},
            "shell" {},
            "source-code" {},
            "tagging" {},
            "tap" {},
            "test-runners" {},
            "testing" {},
            "tools-deps" {},
            "upgrade" {},
            "validations" {},
            "workspace" {}})

(def ws-pages {"bases" [],
               "changes" [],
               "components" [],
               "configs" [],
               "interface" [],
               "messages" [],
               "name" [],
               "old" [],
               "paths" [],
               "projects" [],
               "settings" [],
               "user-input" [],
               "version" [],
               "ws-dir" [],
               "ws-local-dir" [],
               "ws-reader" [],
               "ws-type" []})
